[神器0005] ダメージを与えたとき0-0-0-0-0を別ディメンションに連行してしまう不具合を修正
ProjectTSB/TheSkyBlessing pull request #1102
Opened 2022-07-16 14:34 UTC by uran247

エンティティ読み込みの仕様変更前に作ってたから問題と思ってなかった・・・

2022-07-16 20:20 UTC, ChenCMD requested changes

2022-07-16 20:20 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/trigger/3.1.2.damage.mcfunction
> +    execute in overworld run tp 0-0-0-0-0 0.0 0.0 0.0
そもそも19行目の部分にin overworldをつけちゃえば良さそうではある

2022-07-17 08:23 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/trigger/3.1.2.damage.mcfunction
> +    execute in overworld run tp 0-0-0-0-0 0.0 0.0 0.0
それをやると35行目で0-0-0-0-0を検知できなくなるので動作しなくなる

2022-07-17 08:24 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/trigger/3.1.2.damage.mcfunction
> +    execute in overworld run tp 0-0-0-0-0 0.0 0.0 0.0
なるほど、じゃあこれで

2022-07-17 08:24 UTC, ChenCMD approved these changes

2022-07-17 08:25 UTC, merged