🔧 [神器279]C-4を作成
ProjectTSB/TheSkyBlessing pull request #1129
Opened 2022-07-23 19:16 UTC by quikku

2022-08-24 10:19 UTC, ChenCMD requested changes

2022-08-24 10:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0279.c-4/trigger/3.main.mcfunction
> +    tag @s add 7R.This
普通にthisついてない？

2022-08-24 10:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0279.c-4/trigger/wall_check.mcfunction
> +    execute at @e[type=marker,tag=7R.WallCheker,distance=..3,sort=nearest,limit=1] positioned ~ ~-0.5 ~ run function asset:sacred_treasure/0279.c-4/trigger/c4_summon
ここat @sにした方が後が軽そう

2022-08-27 20:43 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0279.c-4/trigger/wall_check.mcfunction
> +    execute at @e[type=marker,tag=7R.WallCheker,distance=..3,sort=nearest,limit=1] positioned ~ ~-0.5 ~ run function asset:sacred_treasure/0279.c-4/trigger/c4_summon
それ位置ズレない？

2022-09-02 10:25 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0279.c-4/trigger/wall_check.mcfunction
> +    execute at @e[type=marker,tag=7R.WallCheker,distance=..3,sort=nearest,limit=1] positioned ~ ~-0.5 ~ run function asset:sacred_treasure/0279.c-4/trigger/c4_summon
これね、当時の私が何を思ってたのか知らないんですが多分こういうことをすると後が綺麗にできるって言いたかったんだと思います
```suggestion
    execute as @e[type=marker,tag=7R.WallCheker,distance=..3,sort=nearest,limit=1] at @s positioned ~ ~-0.5 ~ run function asset:sacred_treasure/0279.c-4/trigger/c4_summon
```
c4_summonで使われてる`@s`は`@p[tag=this]`にできる

2022-09-02 10:25 UTC, ChenCMD requested changes
comment

2022-09-02 19:12 UTC, ChenCMD approved these changes

2023-03-02 05:14 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0279.c-4/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Urban', 'Nyaptov', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Urban", "Nyaptov", "Rumor"]
```

2024-10-20 11:04 UTC, closed without merging