🚸 世界のナイフの性能変更
ProjectTSB/TheSkyBlessing pull request #1151
Opened 2022-08-06 09:04 UTC by quikku

2022-09-08 15:16 UTC, Lapis-LJA requested changes
これ以外は動作チェックしてないのでわからないです

2022-09-08 15:16 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0837.the_world_knife/trigger/2.check_condition.mcfunction
> +    # もしいたらテレポ
テレポ..?

2022-09-08 15:16 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0837.the_world_knife/trigger/2.check_condition.mcfunction
> +    # もしいたらテレポ
ええ...（困惑）

2024-04-20 16:32 UTC, ChenCMD approved these changes

2024-04-20 16:34 UTC, merged