🔧 [神器566～569]大賢者装備を作成
ProjectTSB/TheSkyBlessing pull request #1154
Opened 2022-08-11 12:52 UTC by quikku

2022-09-08 15:09 UTC, Lapis-LJA requested changes

2022-09-08 15:09 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0566.great_sage_helmet/equip/3.main.mcfunction
> +    playsound minecraft:block.enchantment_table.use master @a ~ ~ ~ 0.8 1
masterよりplayerのほうがいいかも

2022-09-08 15:09 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0567.great_sage_chestplate/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
ニャは使えないって話ｊ(ry

2022-09-08 15:09 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0568.great_sage_leggings/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
ニャ(ry

2022-09-08 15:09 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0569.great_sage_boots/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
(ry

2022-09-08 15:09 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0569.great_sage_boots/trigger/dis_equip/main.mcfunction
> +    function api:player_modifier/attack/physical/remove
596になってる

2022-09-08 15:09 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0566.great_sage_helmet/equip/fullset_remove.mcfunction
> +    playsound minecraft:entity.allay.item_thrown ambient @a ~ ~ ~ 1 1.4
ambitentよりplayerのほうがよさそう

2023-03-02 05:04 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0566.great_sage_helmet/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-03-02 05:04 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0567.great_sage_chestplate/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-03-02 05:04 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0568.great_sage_leggings/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-03-02 05:04 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0569.great_sage_boots/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2024-04-20 13:38 UTC, haiiro2gou requested changes

2024-04-20 13:38 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0566.great_sage_helmet/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['[{"text":"大賢者エリュサスの祈りが込められた帽子","color":"#FED4FF"}]','{"text":"この衣服はエリュサスの写し身そのものだ","color":"#FED4FF"}','{"text":"魔法耐性+7.5% 魔法攻撃+7.5%","color":"
魔法耐性攻撃の行が消えてるので直してね

2024-04-20 13:38 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0567.great_sage_chestplate/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['[{"text":"大賢者エリュサスの祈りが込められたローブ","color":"#FED4FF"}]','{"text":"この衣服はエリュサスの写し身そのものだ","color":"#FED4FF"}','{"text":"魔法耐性+7.5% 魔法攻撃+7.5%","color":
同上

2024-04-20 13:38 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0568.great_sage_leggings/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['[{"text":"大賢者エリュサスの祈りが込められたローブ","color":"#FED4FF"}]','{"text":"この衣服はエリュサスの写し身そのものだ","color":"#FED4FF"}','{"text":"魔法耐性+7.5% 魔法攻撃+7.5%","color":
同上

2024-04-20 13:38 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0569.great_sage_boots/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['[{"text":"大賢者エリュサスの祈りが込められたブーツ","color":"#FED4FF"}]','{"text":"この衣服はエリュサスの写し身そのものだ","color":"#FED4FF"}','{"text":"魔法耐性+7.5% 魔法攻撃+7.5%","color":
同上

2024-04-21 15:14 UTC, haiiro2gou commented
ニャプは使えないんじゃないんだっけ

2024-04-21 15:21 UTC, quikku commented
スプレの方を修正
ニャが使えない理由なさそう（エリュサスが過激な奴であることを除いて）

2024-04-21 16:19 UTC, haiiro2gou approved these changes
ニャプ様がそう言うなら…

2024-10-20 11:12 UTC, closed without merging