:technologist: 難度値を取得できるAPIを作成
ProjectTSB/TheSkyBlessing pull request #1202
Opened 2022-09-07 18:56 UTC by ChenCMD

2022-09-08 14:31 UTC, Lapis-LJA requested changes

2022-09-08 14:31 UTC, Lapis-LJA commented on TheSkyBlessing/data/core/functions/_index.d.mcfunction
> +# TODO 上記のGlobal VarsをPrivateにしてAPIに以降する
些細なことだけど以降→移行

2022-09-09 17:29 UTC, Lapis-LJA commented on TheSkyBlessing/data/core/functions/_index.d.mcfunction
> +#   api:**
apiの下全てが対象なのは仕様？

2022-09-09 17:34 UTC, ChenCMD commented on TheSkyBlessing/data/core/functions/_index.d.mcfunction
> +#   api:**
後から定義増やすときに細かいの何個も作ってもそれに見合った恩恵が無い

2022-09-09 17:35 UTC, Lapis-LJA commented on TheSkyBlessing/data/core/functions/_index.d.mcfunction
> +#   api:**
それならよさそう

2022-09-09 17:36 UTC, Lapis-LJA approved these changes
よさそう

2022-10-29 19:36 UTC, merged