✨ 落下ダメージが最大体力に依存するように
ProjectTSB/TheSkyBlessing pull request #1207
Opened 2022-09-09 17:28 UTC by ChenCMD

Fixes #1176

2023-03-03 19:03 UTC, uran247 commented on TheSkyBlessing/data/player_manager/functions/fall_damage/check_invulnerable.mcfunction
> +#> player_manager:fall_damage/check_invulnerable
deal_damage_for_vulnerable_playerって感じの名前のほうがいいなー

2024-01-29 07:51 UTC, haiiro2gou commented on TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/deal.mcfunction
> +    data modify storage lib: Argument.FixedDamage set value false
lib:damage/だとapi: Argument.FixedDamageに値が入ってるとlib側の変数が反映されないため耐性を無視してくるっぽい

2024-01-29 07:55 UTC, haiiro2gou commented on TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/get_vars.mcfunction
> +    execute unless data storage api: ActiveEffects[{Id:8}] run scoreboard players set $JumpBoost Temporary -10
apiからエフェクトを拾ってなさそう
(masterマージしたら書き換えも必要そう)

2024-09-22 22:35 UTC, ChenCMD commented on TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/get_vars.mcfunction
> +    execute unless data storage api: ActiveEffects[{Id:8}] run scoreboard players set $JumpBoost Temporary -10
現時点では対応しないかも、どちらにせよジャンプ力を上げるならバニラのジャンプブーストを付けるしか無いので

2024-09-29 04:10 UTC, haiiro2gou commented on TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/get_vars.mcfunction
> +    execute unless data storage api: ActiveEffects[{Id:8}] run scoreboard players set $JumpBoost Temporary -10
じゃあいいか

2024-09-29 04:47 UTC, haiiro2gou requested changes
たぶんこれだけ

2024-09-29 04:47 UTC, haiiro2gou commented on TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/calc.mcfunction
> +# $FixedDamagePart(e5) = $DamageableFallDistance(e1) * 0.8(e1) * 1(e3)
```suggestion
# $FixedDamagePart(e5) = $DamageableFallDistance(e1) * 0.5(e1) * 1(e3)
```

2024-09-29 05:01 UTC, haiiro2gou approved these changes

2024-09-29 05:02 UTC, merged