🔧 [神器600]Xtalを作成
ProjectTSB/TheSkyBlessing pull request #1242
Opened 2022-09-24 03:06 UTC by quikku

2023-03-02 04:56 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0600.xtal/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo.IsRangeAttack set value every
```suggestion
    data modify storage asset:sacred_treasure AttackInfo.IsRangeAttack set value "every"
```

2023-03-02 04:56 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0600.xtal/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Urban', 'Nyaptov', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Urban", "Nyaptov", "Rumor"]
```

2023-12-27 17:03 UTC, haiiro2gou requested changes
攻撃範囲が3mなのにgiveでは攻撃範囲が4mと表記されているので修正してほしい

2023-12-27 17:03 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0600.xtal/trigger/5.slash.mcfunction
> +        execute as @e[type=#lib:living,tag=Enemy,tag=!Uninterferable,distance=..3] positioned ^ ^ ^3 run function lib:damage/
asとpositionedが逆なのでプレイヤー起点で背面にも攻撃することになってそう

2024-04-20 15:12 UTC, haiiro2gou approved these changes
つえー

2024-04-20 16:35 UTC, ChenCMD approved these changes

2024-04-20 17:03 UTC, merged