🔧 [神器999]セクスタプル・アルティマを作成
ProjectTSB/TheSkyBlessing pull request #1251
Opened 2022-10-01 18:49 UTC by quikku

2023-01-04 19:46 UTC, Lapis-LJA requested changes

2023-01-04 19:46 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0302.call_gun/tick/shot/3.damage.mcfunction
> +        data modify storage lib: Argument.ElementType set value "None"
あまりにも嘘表記すぎる

2023-01-06 04:20 UTC, Lapis-LJA submitted a review, later dismissed

2023-01-06 04:20 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0302.call_gun/summon/2.summon.mcfunction
> +    data modify storage asset:mob Type set value "Friend"
FriendじゃなくてProjectileな気がする

2023-03-02 04:54 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0999.sextaple_ultima/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure Trigger set value onClick
```suggestion
    data modify storage asset:sacred_treasure Trigger set value "onClick"
```

2023-03-02 04:54 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0999.sextaple_ultima/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo.IsRangeAttack set value never
```suggestion
    data modify storage asset:sacred_treasure AttackInfo.IsRangeAttack set value "never"
```

2023-03-02 04:54 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0999.sextaple_ultima/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Urban', 'Wi-ki' , 'Rumor' ]
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Urban", "Wi-ki", "Rumor"]
```

2023-12-27 16:50 UTC, haiiro2gou requested changes
この辺を修正してほしいかも
- マスケットが対象が存在しないときに問答無用で発砲する点
- 神器側に使わないタグ及びスコアの定義が残っている点

2024-04-20 15:30 UTC, haiiro2gou approved these changes
よさげ

2024-04-20 17:10 UTC, ChenCMD approved these changes

2024-04-20 17:11 UTC, merged