ヘルスを割合で取得するAPIを作成
ProjectTSB/TheSkyBlessing pull request #1277
Opened 2022-11-10 20:08 UTC by Chuzume

2022-11-11 08:34 UTC, Lapis-LJA requested changes

2022-11-11 08:34 UTC, Lapis-LJA commented on TheSkyBlessing/data/api/functions/mob/get_health_percent.mcfunction
> +# @within function api:mob/get_max_health
apiならここは@withinではなく@apiであるべきかも

2022-11-17 07:25 UTC, Lapis-LJA approved these changes
よさそう

2022-11-22 08:35 UTC, ChenCMD requested changes

2022-11-22 08:35 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/mob/get_health_percent.mcfunction
> +#declare score_holder $MaxHealth
複数個の宣言の場合はインデントが必要
```suggestion
#> 計算用スコアホルダー
# @private
    #declare score_holder $Health
    #declare score_holder $MaxHealth
```

2022-11-22 08:35 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/mob/get_health_percent.mcfunction
> +    execute store result storage api: Return.HealthPer int 1 run scoreboard players operation $Health Temporary /= $MaxHealth Temporary
これ、Return.HealthPerをintとして返さずにdoubleにして小数点下3桁くらいまで有効な結果(つまり、AbsorptionAmountを1000倍で取得し、storeの時にdouble 0.001)として返すとわかりやすそう

2022-11-23 08:52 UTC, Chuzume commented on TheSkyBlessing/data/api/functions/mob/get_health_percent.mcfunction
> +    execute store result storage api: Return.HealthPer int 1 run scoreboard players operation $Health Temporary /= $MaxHealth Temporary
Double型がいいのはそうなのかもしれませんが、わかりやすさを重視するなら0~100で返ってくるほうがわかりやすくないですか？どうせ得た結果はスコアとかに入れるんですから、そのまま入れられるほうがいいと思います

2022-11-23 12:37 UTC, ChenCMD approved these changes

2022-11-23 12:37 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/mob/get_health_percent.mcfunction
> +#
```suggestion
#
# @output storage api: Return.HealthPer : double
```

2022-11-23 13:11 UTC, merged