両手及び防具に神器を直接giveするAPIを作成
ProjectTSB/TheSkyBlessing pull request #1278
Opened 2022-11-13 06:24 UTC by haiiro2gou

2022-11-13 14:53 UTC, haiiro2gou commented
fork側のactionsがこちらに反映されないようなので
lintをそちらで実行してもらいたいです

2022-11-29 21:01 UTC, ChenCMD commented
> fork側のactionsがこちらに反映されないようなので lintをそちらで実行してもらいたいです

[この記事](https://qiita.com/masato_makino/items/9ed495538ca972551dc6#fork%E3%81%97%E3%81%9F%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AEactions%E8%A8%AD%E5%AE%9A)を参考にActionsを有効にしてみてください(もしこれで出来ない場合はこちらがわでなんとかします

2022-11-29 21:06 UTC, ChenCMD requested changes
`asset_manager:common/context_slot/*`はslotが別の場所で使われないので不要に思える。
後これはAPI設計そのものに関する指摘なのだけど、該当スロットが空欄だったらそのスロットに神器を追加するのではなくitem replaceのような常にそのスロットを神器で上書きするような挙動のほうが求められてそう？

2022-11-30 02:27 UTC, haiiro2gou commented
> > fork側のactionsがこちらに反映されないようなので lintをそちらで実行してもらいたいです
> 
> [この記事](https://qiita.com/masato_makino/items/9ed495538ca972551dc6#fork%E3%81%97%E3%81%9F%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AEactions%E8%A8%AD%E5%AE%9A)を参考にActionsを有効にしてみてください(もしこれで出来ない場合はこちらがわでなんとかします

Actions自体はfork側で動いているのですが、その実行結果がこちらのリポジトリのPRに反映されていないという状況です

2022-12-15 18:12 UTC, ChenCMD requested changes
インベントリがいっぱいの時にreplaceされないバグがあるね、それとそれを修正するにあたって正直giveとreplaceは別のAPIとして分けたほうがきれいに思える
後、Slotは別にintである必要は無いので素直にstringとして受け取ったほうが圧倒的に可読性が上がりそう

2022-12-18 16:08 UTC, haiiro2gou commented
現状では指定slotに神器が入っている状態でreplaceを動かすと、無限増殖などと同様に保護された状態で退避されたアイテムが吐き出されます

2022-12-24 19:43 UTC, ChenCMD approved these changes
miss

2022-12-24 19:43 UTC, ChenCMD requested changes
おそらく、その仕様にすると https://github.com/ProjectTSB/TheSkyBlessing/issues/749 をぶち抜くので正直やめた方がいい、そういう意味でも全体のRequest changesの様な変更リクエスト出したのだけど、どう？
それから、どちらにせよSlotを文字列にするのはやってほしい

2022-12-25 05:06 UTC, haiiro2gou commented
> おそらく、その仕様にすると #749 をぶち抜くので正直やめた方がいい、そういう意味でも全体のRequest changesの様な変更リクエスト出したのだけど、どう？ それから、どちらにせよSlotを文字列にするのはやってほしい

前者については未設定をmainhandの処理に流すように変更した場合#749の問題を解消できると思います
後者については変更済みです

2022-12-25 08:32 UTC, ChenCMD commented
私の見る限りではTSB内の何らかの処理でそのスロットのアイテムが削除されたうえで、そのスロットに対してreplaceをすると削除したにもかかわらずそのアイテムがドロップすると思うのだけどどうかな

2023-01-01 16:18 UTC, haiiro2gou commented
前者のreplaceの処理にデフォルトで流すようにした場合は削除されたアイテムがドロップするという事象は今のところ確認されていません

2023-01-01 19:38 UTC, ChenCMD requested changes

2023-01-01 19:38 UTC, ChenCMD commented on TheSkyBlessing/data/asset/functions/sacred_treasure/common/replace_slot.mcfunction
> +    execute if data storage asset:context {Slot:"head"} run data modify storage asset:context Evacuate set from entity @s Inventory[{Slot:103b}]
削除されたアイテムがドロップしないのはここで直接プレイヤーからNBTを取得しているからだね、TSBにおいてプレイヤーのすべてのNBTは`api:data_get/*`を通して取得すべきなのでそもそも修正すべき....だが、修正すると上記で指摘したような問題が発生するはず。

2023-02-12 21:39 UTC, ChenCMD requested changes

2023-02-12 21:39 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/sacred_treasure/replace/from_id.mcfunction
> +# Argument.Slot
```suggestion
# @input storage api:
#   Argument.ID
#   Argument.Slot
```

2023-02-13 03:37 UTC, haiiro2gou commented
しょうもないミスばかりで申し訳ないです

2023-02-15 10:08 UTC, ChenCMD approved these changes
LGTM

2023-02-15 10:10 UTC, merged