🐛 box指定時にプレイヤーにも神器がgiveされるバグを修正
ProjectTSB/TheSkyBlessing pull request #1286
Opened 2022-11-15 15:31 UTC by haiiro2gou

[![lint-datapack](https://github.com/haiiro2gou/TheSkyBlessing/actions/workflows/datapack-linter.yml/badge.svg?branch=fix%2Fhaiiro_GiveBox)](https://github.com/haiiro2gou/TheSkyBlessing/actions/workflows/datapack-linter.yml)

2022-11-29 20:23 UTC, ChenCMD requested changes

2022-11-29 20:23 UTC, ChenCMD commented on TheSkyBlessing/data/asset/functions/sacred_treasure/common/give.mcfunction
> +    execute unless data storage asset:context {Type:"drop"} unless data storage asset:context {Type:"box"} if score $InvSize Lib matches 36.. as @e[type=item,nbt={Item:{tag:{TSB:{}}}},distance=..0.3]
これはunless2つ書くのではなく、`api:sacred_treasure/give/*`側にType:"give"を付けてifで判定したほうが賢そう(~~そもそも私は最初からなんでそれしてないんだか....。~~)

2022-11-30 23:31 UTC, haiiro2gou commented on TheSkyBlessing/data/asset/functions/sacred_treasure/common/give.mcfunction
> +    execute unless data storage asset:context {Type:"drop"} unless data storage asset:context {Type:"box"} if score $InvSize Lib matches 36.. as @e[type=item,nbt={Item:{tag:{TSB:{}}}},distance=..0.3]
変更しました

2022-12-15 18:12 UTC, ChenCMD approved these changes

2022-12-15 18:15 UTC, merged