:technologist: 最大MPをplayer_modifierで変更できるように
ProjectTSB/TheSkyBlessing pull request #1287
Opened 2022-11-18 16:17 UTC by haiiro2gou

2022-11-29 21:19 UTC, ChenCMD requested changes

2022-11-29 21:19 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/player_modifier/mp_max/add.mcfunction
> +    execute store result score @s MPMax run data get storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].Modifiers.MPMax 100
Modifierという概念のものが最終的に直接MPMaxのスコアを弄ってるのはだいぶ気持ち悪さがある....が逆にどこでこの処理をすればいいかについては現時点では思いつかないので要検討かも

2022-11-30 20:37 UTC, ChenCMD requested changes
Modifiers.MPMaxが初期化されていないので色々問題が発生しそう、初期化は`core:handler/first_join`とかでやってたはず

2022-11-30 20:37 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/player_modifier/mp_max/add.mcfunction
> +    execute store result score @s MPMax run data get storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].Modifiers.MPMax 100
`api:mp/update_max`ってAPIを作ってそこで23行目と同等の処理を行うような形に分離するとそこそこきれいな形になりそう。

2022-12-24 19:46 UTC, ChenCMD requested changes

2023-02-06 19:49 UTC, ChenCMD requested changes
MPMaxが0.01倍した値として保存されてるのが非常に気持ち悪い(し、おそらく誤差が発生する)
原因は`api:modifier/core/common/update_modifier/`が1にModifierを掛けた値で算出されてることだと思うのだけど、同関数のデフォルト値を設定出来るようにして、100をデフォルトにするべき。
後、`player_manager:bonus/update_mp_bonus`の差分の部分に関しては近々別途PRで修正が入るのでそれの変更も汲み取って欲しい
追記: 最後の一文に関してはそれまでに上記を修正してくれたらmerge後にこっちでやるよ、後review遅れてごめんね

2023-08-08 15:29 UTC, haiiro2gou commented
割と丸々変更しました

2023-08-14 19:25 UTC, ChenCMD commented
Review して良いタイミングで Ready for review してくだせ

2023-08-15 02:27 UTC, haiiro2gou commented
今のところ最大体力のModifierについては変更していませんが、最大体力と同様の方針でScoreToMaxHealthに代入することでModifier管理が行えます
しかし、神器のtrigger処理が1種しか発動できない都合、防具などのAttributeModifierをコマンド処理に依存できないのが現状です

2024-02-02 16:52 UTC, haiiro2gou commented
artifact asset側でmodifierを格納する部分を用意したい

2024-09-22 19:09 UTC, ChenCMD requested changes
## `api:modifer/**/remove`

nits: `@input` 書いてくれるのであれば `@output` (`storage api: Removed`) も書いてくれると嬉しいっす

## その他
これは必須ではないんだけど、`api:modifier/core/**/add`, `api:modifier/core/**/remove` はマクロで共通化しちゃってもいいと思う

2024-09-22 19:09 UTC, ChenCMD commented on TheSkyBlessing/data/core/functions/handler/join.mcfunction
> +    function asset:artifact/0002.blessing/trigger/update/mp_bonus
MUST: これが必要になるのであれば、前に言ったこととはちょっと変わってしまうけれど、以前のように player_manager に更新の本体は用意したうえで、API 側に update 用の関数を公開し、祝福とこのファイルはそこを呼び出すべきに思える

2024-09-25 08:16 UTC, haiiro2gou commented
> これは必須ではないんだけど、`api:modifier/core/**/add`, `api:modifier/core/**/remove` はマクロで共通化しちゃってもいいと思う

これは別PR送りにしたいかも

2024-09-25 08:39 UTC, haiiro2gou commented on TheSkyBlessing/data/core/functions/handler/first_join.mcfunction
> +    data modify storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].Modifiers set value {Heal:1d,ReceiveHeal:1d,Attack:{Base:1d,Physical:1d,Magic:1d,None:1d,Fire:1d,Water:1d,Thunder:1d},Defense:{Bas
`Base` まわりの適切な代案が思いつかないので誰か提案してほしい

2024-09-27 12:10 UTC, ChenCMD commented on TheSkyBlessing/data/core/functions/handler/first_join.mcfunction
> +    data modify storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].Modifiers set value {Heal:1d,ReceiveHeal:1d,Attack:{Base:1d,Physical:1d,Magic:1d,None:1d,Fire:1d,Water:1d,Thunder:1d},Defense:{Bas
まずは役割を言語化しよう？

2024-10-03 17:17 UTC, ChenCMD approved these changes

2024-10-03 17:17 UTC, ChenCMD commented on TheSkyBlessing/data/core/functions/load_once.mcfunction
>          #declare score_holder $DefenseBonus
nits: 命名に一貫性が無さそう

2024-10-04 09:56 UTC, haiiro2gou commented on TheSkyBlessing/data/core/functions/load_once.mcfunction
>          #declare score_holder $DefenseBonus
あ！

2024-10-04 19:38 UTC, merged