[神器0976] ブレイブソードの斬撃にFriendタグがついてしまっているのを修正
ProjectTSB/TheSkyBlessing pull request #1304
Opened 2022-12-11 17:40 UTC by Chuzume

これは友達じゃあないな…。

2022-12-11 17:45 UTC, Lapis-LJA approved these changes
ヨシ！

2022-12-12 07:55 UTC, Lapis-LJA reviewed
approveしたけど、ObjectかProjectileつけてもいいかもしれない

2022-12-17 01:44 UTC, ChenCMD requested changes
斬撃はObjectじゃなくてProjectileな気がする

2022-12-17 02:05 UTC, quikku commented
> 斬撃はObjectじゃなくてProjectileな気がする

斬撃自体がなにか敵に対して行動するわけじゃないしObjectじゃない？

2022-12-17 02:13 UTC, ChenCMD commented
> > 斬撃はObjectじゃなくてProjectileな気がする
> 
> 斬撃自体がなにか敵に対して行動するわけじゃないしObjectじゃない？

まぁ悩ましいところだけどまぁじゃあそれでいいか

2022-12-17 02:13 UTC, ChenCMD approved these changes

2022-12-17 02:15 UTC, merged

2022-12-17 03:36 UTC, Chuzume commented
斬撃には判定が全く無いので、Projectileかき消しとか、反射とかされても仕方ないのでObjectにしてます。攻撃判定出してるのが斬撃部分だったらProjectileになんですけどネ