[神器738] ボルテージストライカーの作成
ProjectTSB/TheSkyBlessing pull request #1305
Opened 2022-12-12 14:50 UTC by Lapis-LJA

2023-03-02 04:36 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0738.voltage_striker/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-12-27 14:47 UTC, haiiro2gou approved these changes
よさそう

2024-01-06 03:07 UTC, haiiro2gou requested changes

2024-01-06 03:07 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0738.voltage_striker/trigger/bullet/hit.mcfunction
> +    execute at @a[distance=..160] if score @s KI.UserID = @p UserID run function lib:damage/modifier
```suggestion
    execute at @a[distance=..160] if score @s KI.UserID = @p UserID as @p run function lib:damage/modifier
```
ダメージが補正されないかも

2024-01-06 04:57 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0738.voltage_striker/trigger/bullet/hit.mcfunction
> +    execute at @a[distance=..160] if score @s KI.UserID = @p UserID run function lib:damage/modifier
ここじゃなくてUserIDコピーのとこがミスってそう

2024-01-06 05:01 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0738.voltage_striker/trigger/bullet/hit.mcfunction
> +    execute at @a[distance=..160] if score @s KI.UserID = @p UserID run function lib:damage/modifier
いやそういうことか理解した

2024-01-06 06:50 UTC, haiiro2gou approved these changes
ダメージ表記を160x5にした方がいいかも？（任意）

2024-01-06 06:52 UTC, Lapis-LJA commented
それは別にいいかな(

2024-01-16 10:29 UTC, Lapis-LJA commented
Assetリポジトリに移動

2024-01-16 10:29 UTC, closed without merging