🔧 [mob284]レクシエルV2の作成
ProjectTSB/TheSkyBlessing pull request #1306
Opened 2022-12-13 14:13 UTC by quikku

調整はあとからします

2023-01-12 15:20 UTC, Lapis-LJA requested changes

2023-01-12 15:20 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0285.lexiel_fireball/tick/3.damage.mcfunction
> +        execute as @a[gamemode=!creative,gamemode=!spectator,distance=..3] run function lib:damage/
・ダメージ量が高すぎ
・ElementTypeがWaterになってる
・重要ではないけどgamemode=!crea,!specは!PlayerShouldInvulnerableにしよう

2023-12-29 06:25 UTC, haiiro2gou requested changes

2023-12-29 06:25 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0284.lexiel/tick/armor_stand_check.mcfunction
> +    execute positioned ~ ~0.29 ~ run tag @e[type=armor_stand,tag=7W.Model,distance=..0.01,limit=2] add 7W.ModelChangeTarget
```suggestion
    execute positioned ~ ~0.25 ~ run tag @e[type=armor_stand,tag=7W.Model,distance=..0.01,limit=2] add 7W.ModelChangeTarget
```
アマスタは0.25m上にあるみたいなので

2024-10-20 14:01 UTC, closed without merging