🐛 神器のgive実行時にTypeがないときに正常に実行されるように
ProjectTSB/TheSkyBlessing pull request #1315
Opened 2022-12-20 15:48 UTC by haiiro2gou

現時点で正常に神器のgiveが実行できないという事態(誤解?)に陥っている原因
発端が自分なのもあって一応一つ変更を提示
正直mcf直呼び出しによるgiveを封じる方向での変更は適切ではないと思う

2022-12-20 16:29 UTC, ChenCMD requested changes
｢Typeが指定されていなければgiveを指定する｣と言った実装のほうが適切に思える

2022-12-22 10:19 UTC, haiiro2gou commented
他のasset:context周りの処理を見るにここにresetを置くのも何か違う気がしている

2022-12-24 18:42 UTC, ChenCMD requested changes
そこでリセットを行うこと自体は悪くはないが、それを行う場合、API側でのresetを消し飛ばしたほうが良い

2022-12-26 00:54 UTC, ChenCMD approved these changes
LGTM

2022-12-26 00:54 UTC, merged