絶望の時計の軽量化
ProjectTSB/TheSkyBlessing pull request #1338
Opened 2023-01-02 17:42 UTC by quikku

地面の時計を輝く額縁に
歯車をアーマースタンドに

パーティクルコマンド数を激減させた

2023-01-12 20:59 UTC, ChenCMD requested changes
後もう使われてないparticleのmcf消しちゃってください

2023-01-12 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/gear_gold/spread_summon/.mcfunction
> +summon armor_stand ~ ~10000 ~ {NoGravity:1b,Silent:0b,Invulnerable:1b,Invisible:1b,Tags:["1A.SkillMarker","1A.GearGold","GearInit","Object","Uninterferable"],DisabledSlots:4144959}
この時点では透明なので10000上に召喚する必要ないように思える

2023-01-12 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/gear_silver/spread_summon/5.mcfunction
> +summon armor_stand ~ ~10000 ~ {NoGravity:1b,Silent:0b,Invulnerable:1b,Invisible:1b,Tags:["1A.SkillMarker","1A.GearSilver","GearInit","Object","Uninterferable"],DisabledSlots:4144959}
金と同様

2023-01-13 02:41 UTC, quikku commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/gear_gold/spread_summon/.mcfunction
> +summon armor_stand ~ ~10000 ~ {NoGravity:1b,Silent:0b,Invulnerable:1b,Invisible:1b,Tags:["1A.SkillMarker","1A.GearGold","GearInit","Object","Uninterferable"],DisabledSlots:4144959}
> この時点では透明なので10000上に召喚する必要ないように思える

あとでもう一回確認するけどこれしないと中央から広がってくのみえるのよねたしか

2023-01-14 14:20 UTC, quikku commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/gear_gold/spread_summon/.mcfunction
> +summon armor_stand ~ ~10000 ~ {NoGravity:1b,Silent:0b,Invulnerable:1b,Invisible:1b,Tags:["1A.SkillMarker","1A.GearGold","GearInit","Object","Uninterferable"],DisabledSlots:4144959}
確認とった。10000上に召喚するべきですね

2024-07-09 10:09 UTC, closed without merging