[神器638-641] 精霊の詩衣装備を作成
ProjectTSB/TheSkyBlessing pull request #1351
Opened 2023-01-25 10:59 UTC by Lapis-LJA

2023-03-02 03:17 UTC, tatuharu submitted a review, later dismissed

2023-03-02 03:17 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0638.spirit_garment/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
ダブルクォーテーションに統一してほしい
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

以下と同様の対処
https://github.com/ProjectTSB/TheSkyBlessing/commit/30c2beb2e571cd0886dfb3b5fa584a1ae0e48a53

2023-03-02 04:35 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0639.spirit_garment/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-03-02 04:35 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0640.spirit_garment/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-03-02 04:35 UTC, MT224244 commented on Asset/data/asset/functions/sacred_treasure/0641.spirit_garment/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Nyaptov', 'Wi-ki', 'Rumor']
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Nyaptov", "Wi-ki", "Rumor"]
```

2023-12-28 10:17 UTC, haiiro2gou requested changes
物理耐性ではなく物理攻撃が下がってるので統一してほしい

2023-12-28 10:19 UTC, haiiro2gou commented
あと体力増加がLoreで8、実際の処理では7.5になってるのでこちらも

2023-12-28 10:45 UTC, haiiro2gou requested changes

2023-12-28 10:45 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0638.spirit_garment/trigger/dis_equip/main.mcfunction
> +    attribute @s generic.max_health modifier remove 00000001-0000-0001-0000-027e0000000
```suggestion
    attribute @s generic.max_health modifier remove 00000001-0000-0001-0000-027e0000006
```

2023-12-28 10:45 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0638.spirit_garment/trigger/dis_equip/main.mcfunction
> +    attribute @s generic.max_health modifier remove 00000001-0000-0001-0000-027e0000000
UUIDがおかしいことに気付いた

2023-12-28 10:49 UTC, haiiro2gou approved these changes
よさそう

2024-01-23 09:41 UTC, closed without merging