[神器740] 朧月の妖花の作成
ProjectTSB/TheSkyBlessing pull request #1353
Opened 2023-02-02 12:10 UTC by Lapis-LJA

2023-03-02 03:12 UTC, tatuharu requested changes

2023-03-02 03:12 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0740.flower_of_hazy_moon/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ['Flora', 'Wi-ki', 'Rumor']
ダブルクォーテーションに統一してほしい
```suggestion
    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora", "Wi-ki", "Rumor"]
```
以下と同様の対処
https://github.com/ProjectTSB/TheSkyBlessing/commit/30c2beb2e571cd0886dfb3b5fa584a1ae0e48a53

2023-12-27 14:31 UTC, haiiro2gou approved these changes
良さそう

2023-12-27 14:33 UTC, EllaCoat approved these changes
特に問題なさそう

2024-01-23 09:23 UTC, closed without merging