:bug: api:sacred_treasure/*/from_rarityがgive以外動作しないのを修正
ProjectTSB/TheSkyBlessing pull request #1362
Opened 2023-02-20 16:11 UTC by haiiro2gou

Fixes #1359

2023-02-23 06:38 UTC, ChenCMD reviewed
asset_manager:sacred_tresuare/giveがどんなAPIの種類があるのかを知っているのは気持ち悪いので、直接#asset:sacred_tresuare/giveを呼び出したほうが良い

2023-02-23 06:39 UTC, ChenCMD requested changes
👆

2023-02-23 08:44 UTC, ChenCMD requested changes
これだと多分何も呼び出されない気がする？
事前に突っ込むstorage確認して下せー

2023-02-23 10:56 UTC, haiiro2gou commented
多分こうなるかな
確認不足については申し訳ないです

2023-02-23 11:07 UTC, ChenCMD requested changes
asset_manager:common/context_id/*を使ってidを適切にstash/popする必要がありそうかも

2023-02-24 14:15 UTC, ChenCMD approved these changes
LGTM

2023-02-25 19:31 UTC, merged