🐛 見通しの書でバニラモブの耐性が正しく表示されないバグを修正
ProjectTSB/TheSkyBlessing pull request #1399
Opened 2023-05-25 15:33 UTC by haiiro2gou

AssetMobがないことを検知する形式（現在）か
あらかじめバニラモブに1.0の耐性を付与するか

2023-05-26 14:58 UTC, Lapis-LJA requested changes

2023-05-26 14:58 UTC, Lapis-LJA commented on TheSkyBlessing/data/asset_manager/functions/mob/_index.d.mcfunction
> +#   asset:artifact/0001.book_of_all-seeing/trigger/get_defense_info
ここの定義は必要ないかも

2023-05-26 14:58 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0001.book_of_all-seeing/trigger/get_defense_info.mcfunction
> +    execute if entity @e[tag=01.Target,tag=!AssetMob] run scoreboard players set $Defense Temporary 100
AssetMobじゃなければ$Defenceを100にするではなく、apiで値を取得した際にデータがなければ100を入れるにした方がいいかも

2023-05-26 16:03 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0001.book_of_all-seeing/trigger/get_defense_info.mcfunction
> +    execute if entity @e[tag=01.Target,tag=!AssetMob] run scoreboard players set $Defense Temporary 100
これ既にあったわ

2023-06-04 16:27 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0001.book_of_all-seeing/trigger/get_defense_info.mcfunction
> +    execute if entity @e[tag=01.Target,tag=!AssetMob] run scoreboard players set $Defense Temporary 100
apiが一個前のデータを拾ってそのまま出力してる

2023-06-04 16:30 UTC, haiiro2gou commented on TheSkyBlessing/data/asset_manager/functions/mob/_index.d.mcfunction
> +#   asset:artifact/0001.book_of_all-seeing/trigger/get_defense_info
これないとlinter君に怒られる

2023-06-26 17:11 UTC, haiiro2gou commented
もしかすると２つに分けたほうがいいかもしれない

2023-06-26 17:36 UTC, haiiro2gou commented
あとでPRは分けておきます

2023-06-27 04:48 UTC, ChenCMD approved these changes
:100:

2023-06-27 04:58 UTC, Lapis-LJA approved these changes

2023-06-27 05:00 UTC, merged