斬撃エンティティを作成
ProjectTSB/TheSkyBlessing pull request #1419
Opened 2023-08-13 18:23 UTC by Chuzume

・召喚者からデータ設定して、色や角度を変えれる斬撃エフェクト。
・敵キャラ、神器などに使うことを想定しています

2023-12-22 00:54 UTC, ChenCMD requested changes

2023-12-22 00:54 UTC, ChenCMD commented on Asset/data/asset/functions/mob/9000.slash_entity/_index.d.mcfunction
> +#declare storage 6y0.storage:
```suggestion
#> declares
# @within function asset:mob/9000.slash_entity/**
    #declare tag 6Y0.Init
    #declare tag 6Y0.FacingMarker
    #declare storage 6y0.storage:
```

2023-12-22 00:54 UTC, ChenCMD commented on Asset/data/asset/functions/mob/9000.slash_entity/slash/.mcfunction
> +# @within function asset:**
特定 asset のファイルを呼び出すのは避けたい、召喚処理とかでできないか検討して欲しい

2023-12-22 00:54 UTC, ChenCMD commented on Asset/data/asset/functions/mob/9000.slash_entity/tick/init.mcfunction
> +# 本当は召喚処理で済ませたいが、Tickからじゃないと個人ストレージが取得できない
これは initialize イベントから this が見れないのがおかしいかも、ちょっと core 側で検討する

2023-12-22 00:54 UTC, ChenCMD commented on TheSkyBlessing/data/asset/tags/functions/mob/register.json
> +
register 追加出来てないかも

2024-09-21 23:08 UTC, Chuzume commented
もう必要はないでしょう…

2024-09-21 23:08 UTC, closed without merging