回復トリガーの作成
ProjectTSB/TheSkyBlessing pull request #1422
Opened 2023-08-20 19:01 UTC by Lapis-LJA

fix #1275

2023-12-27 12:15 UTC, EllaCoat approved these changes
特に問題なさそう

2024-01-02 07:26 UTC, Lapis-LJA commented
Healerの特定で詰んで停止してる

2024-03-09 08:48 UTC, haiiro2gou requested changes
今のままで一旦PRを通すならHealerタグの記述を削除しておいてほしいのと、
バニラの回復(ポーションなど)に反応させたくない？ってのと

2024-03-09 09:27 UTC, Lapis-LJA commented
ポーション検知までする意味ある？

2024-03-09 09:34 UTC, haiiro2gou approved these changes
要らないならいいや

2024-03-09 10:18 UTC, ChenCMD approved these changes

2024-03-09 10:18 UTC, merged