Ver1.20.2に対応
ProjectTSB/TheSkyBlessing pull request #1434
Opened 2023-11-11 21:27 UTC by Lapis-LJA

2023-11-12 02:31 UTC, ChenCMD requested changes

2023-11-12 02:31 UTC, ChenCMD commented on .vscode/settings.json
>      "datapack.env.cmdVersion": "1.20",
cmdVersion も 1.20.2 になってなかった？

2023-11-12 07:26 UTC, ChenCMD approved these changes
多分良さそう(だけど Linter が壊れてるので直り次第 merge で)

2023-11-18 02:31 UTC, haiiro2gou requested changes
あと気になったのはこの辺
- `core:load_once.mcf`の体力表示部分が`belowName`->`below_name`
- ゲームルール`enderPearlsVanishOnDeath`が未定義

2023-11-18 02:31 UTC, haiiro2gou commented on TheSkyBlessing/data/api/functions/damage/core/get_status/get_resistance_lv.mcfunction
> +    execute if score $Resistance Temporary matches 127 store result score $Resistance Temporary run data get storage api: active_effects[{Id:"resistance"}].HiddenEffect.Amplifier
```suggestion
    execute if score $Resistance Temporary matches 127 unless data storage api: active_effects[{id:"resistance"}].hidden_effect run scoreboard players set $Resistance Temporary -1
    execute if score $Resistance Temporary matches 127 store result score $Resistance Temporary run data get storage api: active_effects[{id:"resistance"}].hidden_effect.amplifier
```

2023-11-18 02:31 UTC, haiiro2gou commented on TheSkyBlessing/data/api/functions/damage/core/get_status/get_resistance_lv.mcfunction
> +    execute if score $Resistance Temporary matches 127 store result score $Resistance Temporary run data get storage api: active_effects[{Id:"resistance"}].HiddenEffect.Amplifier
HiddenEffectも内部構造が変わってたはず

2023-11-18 02:31 UTC, haiiro2gou commented on TheSkyBlessing/data/api/functions/damage/core/get_status/get_resistance_lv.mcfunction
> +    execute unless data storage api: active_effects[{Id:"resistance"}].Amplifier run scoreboard players set $Resistance Temporary -1
```suggestion
    execute store result score $Resistance Temporary run data get storage api: active_effects[{id:"resistance"}].amplifier
    execute unless data storage api: active_effects[{id:"resistance"}].amplifier run scoreboard players set $Resistance Temporary -1
```

2023-11-18 02:55 UTC, Lapis-LJA commented
> * ゲームルール`enderPearlsVanishOnDeath`が未定義
なんかVSCode上でこれが出ないので保留で

2023-11-26 08:21 UTC, merged