:wrench: ゲームルール：enderPearlsVanishOnDeathを定義
ProjectTSB/TheSkyBlessing pull request #1451
Opened 2023-12-27 13:51 UTC by haiiro2gou

datapack linterのアプデ待ち

2023-12-28 01:32 UTC, EllaCoat approved these changes
コマンド自体に問題はないので

2023-12-30 20:04 UTC, ChenCMD commented
Blocked #1453

2023-12-31 05:53 UTC, haiiro2gou commented
1.20.3以降のDLSにenderPearlsVanishOnDeathがないとかいうトンデモ事態が起きた

2024-04-20 02:11 UTC, ChenCMD requested changes
これ、一旦 linter がこのファイルをチェックしないようにしてください
方法がわからなかったら Discord で聞いてください

2024-04-20 03:25 UTC, ChenCMD approved these changes

2024-04-20 03:25 UTC, merged