進捗のダメージタイプが過去の形式のままであるバグを修正
ProjectTSB/TheSkyBlessing pull request #1457
Opened 2024-01-07 12:39 UTC by EllaCoat

進捗の書き方がダメージタイプが導入されたタイミングで変更されたのでそれに関するバグ修正

2024-01-07 14:37 UTC, haiiro2gou requested changes
criterion nameをtriggerをrequirementに変えるなら統一してほしいかも

2024-01-07 14:37 UTC, haiiro2gou commented on TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction
> +        attribute @s generic.max_absorption base set 2048
```suggestion
        scoreboard players set @s MobHealthMax 2048
    #    execute store result score @s MobHealthMax run data get storage asset:mob Health 1
        execute if data storage asset:mob {Type:"Enemy"} run function mob_manager:init/multiplay_multiplier/normal
        execute if data storage asset:mob {Type:"Enemy.Boss"} run function mob_manager:init/multiplay_multiplier/angel
        attribute @s generic.max_absorption base set 2048
```
混ざってる？

2024-01-07 15:19 UTC, haiiro2gou approved these changes

2024-01-26 15:13 UTC, ChenCMD approved these changes

2024-01-26 15:14 UTC, merged