戦闘中判定用のPredicateを作成
ProjectTSB/TheSkyBlessing pull request #1458
Opened 2024-01-11 11:17 UTC by EllaCoat

試作完了

2024-01-24 04:57 UTC, ChenCMD requested changes

2024-01-24 04:57 UTC, ChenCMD commented on TheSkyBlessing/data/lib/predicates/in_battle.json
> +}
predicate を配列にした場合って標準で all_of じゃなかったっけ

2024-01-24 04:57 UTC, ChenCMD commented on TheSkyBlessing/data/core/functions/tick/player/pre.mcfunction
> +    execute if score @s InBattleTick matches ..0 run scoreboard players reset @s InBattleTick
将来のことも考えて player_manager あたりに切り出してしてほしいかも(このファイルは関数の呼び出しだけにしたい

2024-01-24 04:57 UTC, ChenCMD commented on TheSkyBlessing/data/player_manager/functions/manage_tag/.mcfunction
> +    execute if entity @e[tag=Enemy.Boss,distance=..100] run tag @s add PlayerNearbyEnemy
これちょっと負荷大きいから tag=Enery が失敗して PlayerNearbyEnemy が付与されてないときのみの検査でいい気がする

2024-01-24 04:57 UTC, ChenCMD commented on TheSkyBlessing/data/player_manager/functions/manage_tag/_index.d.mcfunction
> +# @public
このタグを public にするのはかなり微妙かも

2024-01-24 10:58 UTC, EllaCoat commented on TheSkyBlessing/data/lib/predicates/in_battle.json
> +}
確かにそんな感じだったするから、後で直しとく

2024-01-24 11:02 UTC, EllaCoat commented on TheSkyBlessing/data/player_manager/functions/manage_tag/.mcfunction
> +    execute if entity @e[tag=Enemy.Boss,distance=..100] run tag @s add PlayerNearbyEnemy
ちょっとあまり理解できていない
PlayerNearbyEnemyを外す処理はどうすればいい感じかしら？

2024-01-24 11:03 UTC, EllaCoat commented on TheSkyBlessing/data/player_manager/functions/manage_tag/_index.d.mcfunction
> +# @public
@withinでのpredicateの指定がよくわかっていないんだけどどう書けばいいんだっけか

2024-01-24 11:22 UTC, ChenCMD commented on TheSkyBlessing/data/player_manager/functions/manage_tag/.mcfunction
> +    execute if entity @e[tag=Enemy.Boss,distance=..100] run tag @s add PlayerNearbyEnemy
や、14 行目を PlayerNearbyEnemy が付いていないときのみのチェックにしようって話かな

2024-01-24 11:57 UTC, EllaCoat commented on TheSkyBlessing/data/player_manager/functions/manage_tag/.mcfunction
> +    execute if entity @e[tag=Enemy.Boss,distance=..100] run tag @s add PlayerNearbyEnemy
あー理解した了解

2024-02-09 04:47 UTC, ChenCMD approved these changes
よさそう〜

2024-02-09 04:49 UTC, merged