:technologist: 装備時のModifier処理をcore内部で行うように
ProjectTSB/TheSkyBlessing pull request #1485
Opened 2024-03-25 05:49 UTC by haiiro2gou

2024-07-29 09:46 UTC, Lapis-LJA requested changes

2024-07-29 09:46 UTC, Lapis-LJA commented on TheSkyBlessing/data/asset_manager/functions/artifact/create/modifier/.mcfunction
> +    execute if data storage asset:artifact Modifier{Type:"receiveHeal"} run data modify storage asset:artifact Line[1] set value '"回復(受)"'
回復量、被回復量にしよう

2024-10-14 10:35 UTC, ChenCMD requested changes
IMAO: 一案ではあるけど、`Modifier.Type` は `attackBase` みたいな camelCase じゃなくて、`attack/base` みたいな path-like な記法にしてしまうのも手かも。例えば、そういった記法にすると `asset_manager:artifact/triggers/equipments/update_effect/modifier/remove/custom` とかでわざわざ if 分岐をせずにマクロ的にアクセスできる

2024-10-14 11:37 UTC, haiiro2gou commented on TheSkyBlessing/data/asset_manager/functions/artifact/create/set_lore.mcfunction
> +    execute if data storage asset:artifact Item.tag.diplay.Lore[0] run data modify storage asset:artifact Item.tag.display.Lore append value '""'
なんでこんなとこだけ1文字消えてるの～

2024-10-14 11:41 UTC, haiiro2gou commented on TheSkyBlessing/data/asset/functions/artifact/common/give.mcfunction
じゃあ消しとく

2024-10-14 12:25 UTC, haiiro2gou commented on TheSkyBlessing/data/asset_manager/loot_tables/artifact/generate_lore/modifier.json
> +                                    }
初耳学だった

2024-10-14 12:28 UTC, ChenCMD commented on TheSkyBlessing/data/asset_manager/loot_tables/artifact/generate_lore/modifier.json
> +                                    }
こういうところで使われてたりする
https://github.com/ProjectTSB/TheSkyBlessing/blob/cbac59c1cbae5237e98984191452ecfadbca17f9/TheSkyBlessing/data/player_manager/functions/actionbar/.mcfunction#L9

2024-10-14 12:53 UTC, haiiro2gou commented
> IMAO: 一案ではあるけど、`Modifier.Type` は `attackBase` みたいな camelCase じゃなくて、`attack/base` みたいな path-like な記法にしてしまうのも手かも。例えば、そういった記法にすると `asset_manager:artifact/triggers/equipments/update_effect/modifier/remove/custom` とかでわざわざ if 分岐をせずにマクロ的にアクセスできる

これはバニラのAttributeModifiersのことを考えるとif分岐が欲しくなる

2024-10-14 12:59 UTC, ChenCMD commented
> これはバニラのAttributeModifiersのことを考えるとif分岐が欲しくなる
バニラ判定はこれでいい
https://github.com/ProjectTSB/TheSkyBlessing/blob/dev/Chuzume_MobAssetV3/TheSkyBlessing/data/asset_manager/functions/mob/triggers/death/death.m.mcfunction#L8-L9

2024-10-18 11:46 UTC, haiiro2gou commented
@ChenCMD れびゅーたのんだ

2024-10-26 16:33 UTC, haiiro2gou commented
マクロ化うんぬんは他のトリガーと一緒に進めることにしたので置いておく

2024-11-04 06:54 UTC, closed without merging