:technologist: Triggerの並列化
ProjectTSB/TheSkyBlessing pull request #1489
Opened 2024-04-01 07:22 UTC by haiiro2gou

2024-09-22 20:23 UTC, ChenCMD commented
一旦先に Conflict 解消してください (クールダウン周りとか新仕様に対応できてなさそうなので)

2024-09-22 20:23 UTC, ChenCMD requested changes
☝️

2024-10-01 08:17 UTC, haiiro2gou commented
確かに新クールダウンシステムと前提からかち合ってる気がする

2024-10-22 16:20 UTC, haiiro2gou commented
なにやら挙動が怪しいので確認を兼ねて封印

2024-11-04 06:55 UTC, closed without merging