:wheelchair: api:data_getを実行時該当ストレージを一旦削除するように
ProjectTSB/TheSkyBlessing pull request #1496
Opened 2024-04-08 10:02 UTC by haiiro2gou

2024-05-18 07:54 UTC, ChenCMD requested changes
Nullable な場合はそこを消すだけじゃなくて selected_item(_fetch) みたいに、DataCache 側にも工夫をいれる必要があるはずなので一緒にやる必要がありそう

2024-05-18 07:54 UTC, ChenCMD requested changes
Nullable な場合はそこを消すだけじゃなくて selected_item(_fetch) みたいに、DataCache 側にも工夫をいれる必要があるはずなので一緒にやる必要がありそう

2024-05-19 14:36 UTC, haiiro2gou commented
playerがnullを取りかねないような値は切り替えたけど
他entityにも対応させるつもりなら全部fetchしてしまった方がいいのでは…？

2024-05-24 12:25 UTC, ChenCMD commented
data_get はそもそもパフォーマンスの観点から利用されてるに過ぎないもので、これを非 player に使うかの判断は非常に難しいことから一律に player 限定とするのが楽に思えるね

2024-05-24 14:57 UTC, haiiro2gou commented
明らかにプレイヤーが値を持たないmcfはこのまま置いたままで大丈夫？

2024-05-24 15:04 UTC, haiiro2gou commented
エンティティ共通nbtか、了解
じゃあこの状態でレビューお願いします

2024-07-28 09:24 UTC, ChenCMD approved these changes

2024-07-28 09:24 UTC, merged