反射弾ライブラリ実装
ProjectTSB/TheSkyBlessing pull request #1506
Opened 2024-05-09 16:19 UTC by komaramune

2024-05-09 18:37 UTC, quikku commented
良さそう

2024-09-01 07:01 UTC, haiiro2gou requested changes
作図した感じ正しそうなので確認したのでこれだけ直してね

2024-09-01 14:46 UTC, haiiro2gou approved these changes

2024-09-01 15:33 UTC, ChenCMD approved these changes

2024-09-01 15:33 UTC, merged