:technologist: Mob体力のスコア化
ProjectTSB/TheSkyBlessing pull request #1509
Opened 2024-05-19 16:57 UTC by haiiro2gou

2024-06-25 09:23 UTC, Lapis-LJA approved these changes
実際ゲーム内で確認して問題なさそうだった

2024-07-11 09:33 UTC, Lapis-LJA requested changes
Mobの"現在の体力"を取得できるAPI、無くない？

2024-07-18 01:42 UTC, haiiro2gou commented
APIで返したほうがいいのかな
MobHealthスコアがほぼそのままだけど

2024-07-18 01:54 UTC, Lapis-LJA commented
MobHealthはAsset側じゃ未定義のスコアだね

2024-07-18 15:20 UTC, haiiro2gou commented
実装しとく

2024-07-21 06:43 UTC, Lapis-LJA approved these changes
よさそう

2024-07-21 09:37 UTC, ChenCMD requested changes

2024-07-21 09:37 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/heal/core/non-player.mcfunction
>      scoreboard players operation $Health Temporary += $Heal Temporary
$Heal の指数合ってる？

2024-07-21 09:37 UTC, ChenCMD commented on TheSkyBlessing/data/api/functions/damage/core/health_subtract/non-player.mcfunction
> +    execute if score $Health Temporary matches 1.. if entity @s[type=!#lib:undead] run summon area_effect_cloud ~ ~ ~ {Duration:14,Age:4,effects:[{id:"resistance",amplifier:127b,duration:1,show_parti
↑で `damage @s 0` を与えてるならこの演出は不要？

2024-07-28 09:15 UTC, ChenCMD approved these changes
LGTM!

2024-07-28 09:16 UTC, merged