:technologist: 防具セットが加工機から同時に複数部位出現するように
ProjectTSB/TheSkyBlessing pull request #1520
Opened 2024-07-28 10:54 UTC by haiiro2gou

register総取っ換え～

2024-09-21 05:11 UTC, ChenCMD requested changes
tellraw 消してね、あとコメント増やしてほしいのと、コードの変更に現状で現れてない変更がありそうなのでコメントかなにかでいいから書いて欲しい

2024-09-22 05:31 UTC, haiiro2gou commented
これをマージするとregister処理で登録するidがint配列になる

2024-09-22 20:18 UTC, ChenCMD commented on TheSkyBlessing/data/asset_manager/functions/artifact/give/.mcfunction
> +    scoreboard players operation $Pulls Temporary /= $100 Const
want: もう少し具体的に、どういう確立計算をしているかを書いて欲しい

2024-09-22 20:18 UTC, ChenCMD requested changes
↑

2024-09-23 17:28 UTC, ChenCMD approved these changes

2024-09-26 00:47 UTC, ChenCMD commented
コンフリクトなおして〜〜〜

2024-09-26 17:18 UTC, merged