ObjectAssetでInit処理を作れるようになった
ProjectTSB/TheSkyBlessing pull request #1537
Opened 2024-09-16 23:44 UTC by Chuzume

召喚時に一回だけ実行される処理です。
もちろん継承可能。

2024-09-17 04:53 UTC, EllaCoat requested changes
そこ以外は特に問題なさそう

2024-09-17 04:53 UTC, EllaCoat commented on TheSkyBlessing/data/asset_manager/functions/object/summon/init.mcfunction
7～9行目のフィールドを取り出すコードは
25~27行目でフィールドの初期設定を行った後にしたほうが良いと思う
そうしないとoh_my_datを前に起動したやつから取り出すことになるかも

2024-09-19 09:27 UTC, EllaCoat requested changes
再度指摘する感じになってしまって申し訳なし

2024-09-19 09:27 UTC, EllaCoat commented on TheSkyBlessing/data/asset_manager/functions/object/summon/init.mcfunction
>  # フィールド
ちぇん氏に聞きながら確認したところ、
24行目から29行目、
要するにフィールドを設定するところと、フィールドを取り出すところのコードがいらない

2024-09-21 04:40 UTC, ChenCMD approved these changes

2024-09-21 06:01 UTC, EllaCoat approved these changes
これならよさそう

2024-09-21 06:18 UTC, merged