:sparkles: AbsorptionAPI を作成
ProjectTSB/TheSkyBlessing pull request #1581
Opened 2024-10-17 12:49 UTC by ChenCMD

2024-10-18 18:30 UTC, haiiro2gou requested changes
imho: Argumentを直でマクロに突っ込んで大丈夫なのかな
余計な要素まで読み込んで重くなったりしそう

2024-10-18 18:30 UTC, haiiro2gou commented on TheSkyBlessing/data/player_manager/functions/absorption/.mcfunction
> +function lib:array/session/close
nits: インデント揃えたくない？

2024-10-18 18:30 UTC, haiiro2gou commented on TheSkyBlessing/data/api/functions/entity/player/absorption/add.mcfunction
> +# また、その UUID の全ての緩衝体力が消費された時、Argument.WipeCallback が呼び出されます。
```suggestion
# また、その UUID の全ての緩衝体力が消費された時、Argument.WipedCallback が呼び出されます。
```

2024-10-19 04:56 UTC, ChenCMD commented
> imho: Argumentを直でマクロに突っ込んで大丈夫なのかな
> 余計な要素まで読み込んで重くなったりしそう

多分大丈夫なきはするし、だめだとしてもそれは Argument が適切にリセットされてない側に問題があると思う

2024-10-19 09:20 UTC, haiiro2gou commented
> > imho: Argumentを直でマクロに突っ込んで大丈夫なのかな
> > 余計な要素まで読み込んで重くなったりしそう
> 
> 多分大丈夫なきはするし、だめだとしてもそれは Argument が適切にリセットされてない側に問題があると思う

たしかに

2024-10-19 09:20 UTC, haiiro2gou approved these changes

2024-10-19 09:23 UTC, merged