デバッグ用Effect付与functionを作成
ProjectTSB/TheSkyBlessing pull request #1594
Opened 2024-10-23 15:29 UTC by Lapis-LJA

2024-10-24 10:54 UTC, haiiro2gou requested changes
他のArgumentが必要な場合もあるので
ComponentでArgument丸ごと拾えるようにしたほうがいいのかもしれない

2024-10-25 04:19 UTC, Lapis-LJA commented
function debug:effect/give.m {ID:9999,Duration:9999} みたいな感じ？

2024-10-25 09:37 UTC, haiiro2gou commented
そういうこと

2024-10-26 08:41 UTC, ChenCMD approved these changes

2024-10-26 08:41 UTC, haiiro2gou approved these changes

2024-10-26 08:42 UTC, merged