:technologist: api:mob/deal_dummy_damage を実装
ProjectTSB/TheSkyBlessing pull request #1711
Opened 2024-12-21 08:03 UTC by ChenCMD

Asset とかでそのまま damage コマンドを使われると entity_finder が動くので

2024-12-23 04:12 UTC, haiiro2gou requested changes
Q: `api: Argument.Attacker` って他の所で使ってた気がするんだけど、どうだっけ？

2024-12-23 04:12 UTC, haiiro2gou commented on TheSkyBlessing/data/api/functions/mob/deal_dummy_damage.mcfunction
> +    data remove storage lib: Argument.Attacker
MUST: `lib:` ではない

2024-12-26 03:53 UTC, ChenCMD commented
> Q: `api: Argument.Attacker` って他の所で使ってた気がするんだけど、どうだっけ？

player への攻撃時に使われてそうではあった、ただ今回の処理は non-player なので大丈夫そう

2024-12-26 04:10 UTC, haiiro2gou commented
> player への攻撃時に使われてそうではあった、ただ今回の処理は non-player なので大丈夫そう

API叩いた時点で `Argument.Attacker` が消えるので
ライドミサイルみたいにプレイヤーと敵を同時に巻き込むとバグりそう

2024-12-26 04:12 UTC, ChenCMD commented
> ライドミサイルみたいにプレイヤーと敵を同時に巻き込むとバグりそう

真に両方に同時にダメージを与えることは無いはずで、ライドミサイルとかも player と non-player 別に DamageAPI 呼び出してる

2024-12-26 04:20 UTC, haiiro2gou commented
自爆命令は確か一括だよ

2024-12-26 04:22 UTC, haiiro2gou commented
あと前段階で設定した変数がひっそりと変更されて消えるのはバグを呼び起こしそうなのでなんとかならんか

2024-12-26 04:53 UTC, ChenCMD commented
じゃあこれで

2024-12-26 05:36 UTC, haiiro2gou approved these changes
LGTM

2024-12-26 05:37 UTC, merged