[神器0005]マスケット銃（マッチロック）の作成
ProjectTSB/TheSkyBlessing pull request #367
Opened 2021-08-03 17:12 UTC by uran247

2021-08-30 08:59 UTC, ChenCMD requested changes

2021-08-30 08:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/3.1.2.damage.mcfunction
> +    execute as @e[type=#lib:living,tag=5.BulletHit,distance=..9.5,sort=furthest,limit=1] run function lib:damage/
プレイヤーを特定してlib:damage/modifierを実行しない場合Mobが攻撃元を特定できない+神による補正もかからないので可能であれば実行すべき

2022-04-24 09:53 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/3.main.mcfunction
> +    #declare tag 5.MatchlockIndicator
修正完了

2022-04-24 09:53 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/3.1.1.flying.mcfunction
> +    execute as @s at @s run function lib:motion/
修正完了

2022-04-24 09:54 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/3.main.mcfunction
> +    data modify entity @e[type=snowball,tag=5.MatchlockInit,distance=..3,limit=1] Owner set from entity @s UUID
ユーザーIDのスコアを使うようにしたため削除した

2022-04-24 09:54 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/3.main.mcfunction
> +    function lib:forward_spreader/circle
修正完了

2022-04-24 09:54 UTC, uran247 commented on Asset/data/asset/predicates/sacred_treasure/0005.musket_matchlock/is_ride_on_snowball.json
> +  }
修正完了

2022-04-24 09:54 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/3.1.2.damage.mcfunction
> +    execute as @e[type=#lib:living,tag=5.BulletHit,distance=..9.5,sort=furthest,limit=1] run function lib:damage/
修正完了

2022-05-04 18:39 UTC, merged