Dev/tatuharu 233
ProjectTSB/TheSkyBlessing pull request #378
Opened 2021-08-11 06:37 UTC by tatuharu

2021-08-12 08:51 UTC, ChenCMD requested changes
3.mainに書かれてる処理、set_mpに移すことで一つのスコアボードで実現できる気がする

2021-08-12 08:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0233.reversal/3.main.mcfunction
> +    scoreboard objectives add 6H.SetMP dummy
スコアボードの宣言は0.loadでお願いしたい

2021-08-12 08:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0233.reversal/set_mp.mcfunction
> +execute as @s run function lib:mp/set
as @sが要らない
```suggestion
function lib:mp/set
```

2021-08-12 08:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0233.reversal/_index.d.mcfunction
> +    #declare objective 6H.SetMP
この宣言は0.loadに書く場合不要

2022-01-12 15:17 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0233.reversal/3.main.mcfunction
> +    scoreboard objectives add 6H.SetMP dummy
0.loadに記載するように変更

2022-01-12 15:18 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0233.reversal/_index.d.mcfunction
> +    #declare objective 6H.SetMP
0.loadに記載するようにしたので、_index.d.mcfunctionを削除

2022-01-13 13:26 UTC, closed without merging