[神器0089] 魔法の鍬を作成
ProjectTSB/TheSkyBlessing pull request #379
Opened 2021-08-11 06:51 UTC by tatuharu

2021-08-11 06:52 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0089.magic_hoe/2.check_condition.mcfunction
> +        execute store result score $AroundCrops Temporary run clone ~-4 ~-4 ~-4 ~4 ~4 ~4 ~-4 ~-4 ~-4 filtered #asset:sacred_treasure/0088.fertility_hoe/grow_target force
同じ処理だったから別の神器のjson定義見に行っちゃってるけどこれやっていい？

2021-08-11 06:55 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0089.magic_hoe/2.check_condition.mcfunction
> +        execute store result score $AroundCrops Temporary run clone ~-4 ~-4 ~-4 ~4 ~4 ~4 ~-4 ~-4 ~-4 filtered #asset:sacred_treasure/0088.fertility_hoe/grow_target force
この場合88のタグをlibにそれっぽい名前で置けば良さそう、複数の場所から参照されてるあたり汎用的ってことだし

2021-08-29 01:11 UTC, ChenCMD requested changes

2021-08-29 01:11 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0089.magic_hoe/2.check_condition.mcfunction
> +        execute store result score $AroundCrops Temporary run clone ~-4 ~-4 ~-4 ~4 ~4 ~4 ~-4 ~-4 ~-4 filtered #asset:sacred_treasure/0088.fertility_hoe/grow_target force
この場合88のタグをlibにそれっぽい名前で置けば良さそう、複数の場所から参照されてるあたり汎用的ってことだし

2022-07-04 20:48 UTC, closed without merging

2022-07-04 20:49 UTC, ChenCMD commented
古すぎるので作り直すなりして