神器678-671：狐火一式の作成
ProjectTSB/TheSkyBlessing pull request #382
Opened 2021-08-13 13:05 UTC by Lapis-LJA

2021-08-19 06:29 UTC, ChenCMD requested changes
とりあえず #357

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0679.kitsunebi_armor/6.attack.mcfunction
> +    execute at @e[type=#lib:living,tag=Victim,tag=!Uninterferable,distance=..6] run playsound block.fire.ambient master @a ~ ~ ~ 1 0.5 0.6
そもそもUninterferableはVictimにならないから除外する意味はそんなになさそう（こいつは好みの問題かもしれんが）

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0679.kitsunebi_armor/12.kitsunebi_damage.mcfunction
> +    function lib:damage/modifier
このファンクション実行者が敵なんですよねぇ！！！
スコアIDつかってプレイヤーが実行するべきな気がする

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0679.kitsunebi_armor/4.fullset.mcfunction
> +    playsound block.fire.ambient master @a ~ ~ ~ 0.8 0.5 0.6
最小音量は適切でしょうか

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0680.kitsunebi_leggings/3.main.mcfunction
> +    playsound block.fire.ambient master @a ~ ~ ~ 0.8 0.5 0.6
他人に音を聞かせる上にparticleが自分にしか見えない現象
例えるなら隣の住人のテレビの音がクソでかいあれ
最小音量0.6

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0680.kitsunebi_leggings/dis_equip/main.mcfunction
> +    execute if data storage asset:context id.all{head:678,chest:679,legs:680,feet:681} run function asset:sacred_treasure/0679.kitsunebi_armor/14.fullset_dis_equip
タグで良さそうポ

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0679.kitsunebi_armor/dis_equip/main.mcfunction
> +    execute if data storage asset:context id.all{head:678,chest:679,legs:680,feet:681} run function asset:sacred_treasure/0679.kitsunebi_armor/14.fullset_dis_equip
タグでいいんじゃあないか？

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0681.kitsunebi_boots/3.main.mcfunction
> +    playsound block.fire.ambient master @a ~ ~ ~ 0.8 0.5 0.6
はいはい不可視パ＆怪音

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0681.kitsunebi_boots/dis_equip/main.mcfunction
> +    execute if data storage asset:context id.all{head:678,chest:679,legs:680,feet:681} run function asset:sacred_treasure/0679.kitsunebi_armor/14.fullset_dis_equip
タ

2021-09-30 19:10 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0679.kitsunebi_armor/rejoin_process.mcfunction
> +    execute if entity @a[tag=IV.FullSet] run schedule function asset:sacred_treasure/0679.kitsunebi_armor/7.schedule_loop 1t replace
敵用のファンクションは実行しないのけ

2022-01-11 18:09 UTC, closed without merging