[ID:0295] スカルウォリアーを作成
ProjectTSB/TheSkyBlessing pull request #553
Opened 2021-12-24 16:54 UTC by Chuzume

レベル2、どう見てもスケルトンなので島のにぎやかしにどうぞ

2022-05-22 20:56 UTC, ChenCMD requested changes

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/loot_tables/mob/death/0205.skull_warrior.json
> +                            "tag": "{TSB:{ItemMetaData:[\"MobDeathTrigger\",\"BanEntityConditionItem\",\"BanPossession\"],ID:295}}"
```suggestion
                            "tag": "{TSB:{ItemMetaData:[\"MobDeathTrigger\",\"BanEntityConditionItem\",\"BanPossession\"],ID:205}}"
```

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/tags/functions/mob/tick.json
> +        "asset:mob/0205.skull_warrior/tick/1.trigger",
きえてゆ

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/_index.d.mcfunction
> +    #declare tag 5P.Ranged
```suggestion
# @private

#>
# @within function asset:mob/0205.skull_warrior/tick/**
    #declare tag 5P.Melee
    #declare tag 5P.Ranged
```

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/summon/2.summon.mcfunction
> +    data modify storage asset:mob ID set value 295
```suggestion
    data modify storage asset:mob ID set value 205
```

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/summon/2.summon.mcfunction
> +    data modify storage asset:mob Name set value {CustomName:'{"text":"スカルソルジャー"}'}
これPR名と違うのは意図してる？

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/summon/1.trigger.mcfunction
> +execute if data storage asset:context {id:295} run function asset:mob/0205.skull_warrior/summon/2.summon
```suggestion
execute if data storage asset:context {id:205} run function asset:mob/0205.skull_warrior/summon/2.summon
```

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/tick/1.trigger.mcfunction
> +execute if data storage asset:context {id:295} run function asset:mob/0205.skull_warrior/tick/2.tick
```suggestion
execute if data storage asset:context {id:205} run function asset:mob/0205.skull_warrior/tick/2.tick
```

2022-05-22 20:56 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/tick/2.tick.mcfunction
> +    execute if entity @s[tag=5P.Melee] if entity @a[distance=5..16] run function asset:mob/0205.skull_warrior/tick/event/switch_ranged
こうしたほうがよさそう？
```suggestion
    execute if entity @s[tag=5P.Melee] unless entity @a[distance=..5] run function asset:mob/0205.skull_warrior/tick/event/switch_ranged
```

2022-05-23 10:26 UTC, ChenCMD commented on Asset/data/asset/loot_tables/mob/death/0205.skull_warrior.json
> +{
まってこのJSON明らかに古い、適当に他のやつ持ってきてID書き換えて使ってくだせ

2022-05-25 09:27 UTC, Chuzume commented on Asset/data/asset/functions/mob/0205.skull_warrior/summon/2.summon.mcfunction
> +    data modify storage asset:mob Name set value {CustomName:'{"text":"スカルソルジャー"}'}
今ではもうどっちかわかりませんが、ソルジャーのほうが弱そうなのでこっちにならうことにします

2022-05-25 10:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0205.skull_warrior/_index.d.mcfunction
> +# @within function asset:mob/0205.skull_warrior/tick/**
```suggestion
# @within function asset:mob/0205.skull_warrior/**
```

2022-05-25 11:04 UTC, ChenCMD approved these changes

2022-05-25 11:24 UTC, merged