🩹 ルナフレアの性能調整
ProjectTSB/TheSkyBlessing pull request #652
Opened 2021-12-30 23:31 UTC by Chuzume

・ランク4相手に通用するのなら、ということでランク4神器に格上げしました。
・クリック連打すると物凄い連射力になるのでクールダウンを設けました。
・威力が30に、消費MPが10に。（ランク4ザコを目安にしました)
・地形を貫通して相手をターゲッティングできるのを廃止。
・相手がいないところに撃った場合もレーザー攻撃が行われ、MPが消費が発生するように。
・演出面の強化！
・プレイヤーの耳への攻撃力を弱体化

この神器の性能調整を担当していたKaputinaさんには後で話しておきます

2021-12-31 02:06 UTC, kaputina commented
ありがとうございます･･･！

2022-04-20 20:59 UTC, ChenCMD requested changes

2022-04-20 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0609.lunar_flare/trigger/find_target_entity.mcfunction
> +    execute unless entity @s[tag=GX.RecursiveEnd] positioned ~-1 ~-1 ~-1 at @e[type=#lib:living,type=!player,tag=!Object,tag=!Uninterferable,tag=!Projectile,tag=!Npc,dx=0,dy=0,dz=0] run function asse
これだと`~ ~ ~ ~-1 ~-1 ~-1`の範囲をチェックすることになるけど本当にやりたいことはこれだったりしないかな
あと、複数entityがいたときに全部に召喚されるから`limit=1`付けてもよさそうな気がする
```suggestion
    execute unless entity @s[tag=GX.RecursiveEnd] positioned ~-0.5 ~-0.5 ~-0.5 at @e[type=#lib:living,type=!player,tag=!Object,tag=!Uninterferable,tag=!Projectile,tag=!Npc,dx=0,dy=0,dz=0,limit=1] run function asset:sacred_treasure/0609.lunar_flare/trigger/summon_laser_pos
```

2022-04-20 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0609.lunar_flare/trigger/projectile/laser_pos_main.mcfunction
> +    execute as @e[type=marker,tag=GX.LaserPos,scores={GX.BeamTime=1..}] run schedule function asset:sacred_treasure/0609.lunar_flare/trigger/projectile/laser_pos_main 1t replace
これでよさそう
```suggestion
    execute if entity @e[type=marker,tag=GX.LaserPos,scores={GX.BeamTime=1..},limit=1] run schedule function asset:sacred_treasure/0609.lunar_flare/trigger/projectile/laser_pos_main 1t replace
```

2022-04-20 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0609.lunar_flare/trigger/3.main.mcfunction
> +    execute as @e[type=marker,tag=GX.LaserPos] at @s run function asset:sacred_treasure/0609.lunar_flare/trigger/projectile/laser_pos_main
これだとマルチとかの挙動がやばそうなのでこれのほうがいいかも
```suggestion
    schedule function asset:sacred_treasure/0609.lunar_flare/trigger/projectile/laser_pos_main 1t
```

2022-04-20 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0609.lunar_flare/trigger/_index.d.mcfunction
>      #declare tag GX.Target
いらなそう
```suggestion
```

2022-04-20 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0609.lunar_flare/trigger/projectile/laser_pos_main.mcfunction
> +    execute as @e[type=marker,tag=GX.LaserPos,scores={GX.BeamTime=1..}] at @s positioned ~ ~ ~ rotated ~ 90 run function asset:sacred_treasure/0609.lunar_flare/trigger/projectile/summon_laser
不要っぽい
```suggestion
    execute as @e[type=marker,tag=GX.LaserPos,scores={GX.BeamTime=1..}] at @s rotated ~ 90 run function asset:sacred_treasure/0609.lunar_flare/trigger/projectile/summon_laser
```

2022-04-20 20:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0609.lunar_flare/trigger/projectile/hit.mcfunction
> +        execute positioned ~-0.5 ~-0.5 ~-0.5 unless entity @e[type=#lib:living,type=!player,tag=!Uninterferable,dx=0] as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2.5] run funct
こうしないと座標がずれたままかな
```suggestion
        execute positioned ~-0.5 ~-0.5 ~-0.5 unless entity @e[type=#lib:living,type=!player,tag=!Uninterferable,dx=0] positioned ~0.5 ~0.5 ~0.5 as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2.5] run function lib:damage/
```

2022-04-23 04:31 UTC, ChenCMD approved these changes
:100:

2022-04-23 04:31 UTC, merged