🩹 スポナーのスポーン数等の修正
ProjectTSB/TheSkyBlessing pull request #655
Opened 2022-01-02 09:30 UTC by anitmyan

Fix #643

2022-01-02 10:15 UTC, ChenCMD requested changes

2022-01-02 10:15 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/spawner/spawn/nearby_entities/get.mcfunction
> +    execute if data storage asset:spawner NearbyEntitiesCache run function asset_manager:spawner/spawn/nearby_entities/try_get_from_cache/
配列自体は存在することが保証されてしまってるので、これだと常にtrueを返すはずなのでこうする必要がありそう
```suggestion
    execute if data storage asset:spawner NearbyEntitiesCache[0] run function asset_manager:spawner/spawn/nearby_entities/try_get_from_cache/
```

2022-01-02 11:06 UTC, anitmyan commented on TheSkyBlock/data/asset_manager/functions/spawner/spawn/nearby_entities/get.mcfunction
> +    execute if data storage asset:spawner NearbyEntitiesCache run function asset_manager:spawner/spawn/nearby_entities/try_get_from_cache/
ほんとだ、感謝ー！

2022-01-04 07:02 UTC, ChenCMD approved these changes

2022-01-04 07:02 UTC, merged