一部神器、説明文やダメージ表記を修正
ProjectTSB/TheSkyBlessing pull request #657
Opened 2022-01-02 13:45 UTC by quikku

フェニックスが名前と攻撃属性が合わないのを修正
ウォーターマジック、アイスソーサリーのダメージ表記を修正
456ダイス、lore修正
アイスレギンス、防御の部位が違うのを修正

2022-01-04 07:35 UTC, ChenCMD requested changes

2022-01-04 07:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0630.ice_leggings/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CustomNBT set value {HideFlags:68,display:{color:7274495},Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:5
attribute UUID変え忘れてそう

2022-01-04 07:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0373.ice_sorcery/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo.Damage set value ["20.3"]
これでいいはず
```suggestion
    data modify storage asset:sacred_treasure AttackInfo.Damage set value "20.3"
```

2022-01-04 07:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0372.water_magic/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo.Damage set value ["15.2"]
👆

2022-01-08 16:23 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0630.ice_leggings/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CustomNBT set value {HideFlags:68,display:{color:7274495},Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:5
なぜか変え忘れてなかったらしい

2022-01-30 13:55 UTC, ChenCMD approved these changes

2022-01-30 13:56 UTC, merged