ジャックオランタンの強化と眷属の追加
ProjectTSB/TheSkyBlessing pull request #668
Opened 2022-01-06 17:42 UTC by Lapis-LJA

2022-05-16 20:49 UTC, quikku commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/hurt/2.hurt.mcfunction
> +    execute unless entity @s[scores={1N.HurtCount=8..}] run scoreboard players add @s 1N.Surprise 3
これの発動条件聞いてもいい？
モブが二体以上いると明らかにHurtCountが8を超えてSurpriseが増えないのは仕様？
条件次第ではそのままずっと発光しないんだけど

2022-05-19 15:15 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/hurt/2.hurt.mcfunction
> +    execute unless entity @s[scores={1N.HurtCount=8..}] run scoreboard players add @s 1N.Surprise 3
過去の私が何を思ってそうしたのか、もう知る人はいません

2022-05-19 15:24 UTC, quikku commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/hurt/2.hurt.mcfunction
> +    execute unless entity @s[scores={1N.HurtCount=8..}] run scoreboard players add @s 1N.Surprise 3
思ったより数百倍やべー回答がきて絶句
いっそこれオーバーホールしていい？

2022-05-19 15:27 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/hurt/2.hurt.mcfunction
> +    execute unless entity @s[scores={1N.HurtCount=8..}] run scoreboard players add @s 1N.Surprise 3
よくよく考えなくてもやばかったので直した

2022-05-21 10:07 UTC, quikku commented
魔改造終了、これ以上のコミットはバグ修正くらいにとどめておく

2022-05-27 21:34 UTC, Chuzume reviewed
何も問題はないようじゃがのう…

2022-06-17 11:10 UTC, ChenCMD requested changes

2022-06-17 11:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/3.missile/2.check.mcfunction
> +    tag @s[tag=Landing] remove Landing
これ再帰の後ろにあるのびみょい(うるせぇこれから変えるのめんどくさいんじゃいとかならまぁ許す)

2022-06-17 11:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/3.missile/3.tackle.mcfunction
> +    tag @s[tag=Landing] remove Landing
これも同様

2022-06-24 10:21 UTC, ChenCMD approved these changes

2022-06-24 10:37 UTC, merged