Mob234：ハニーフライヤーの作成
ProjectTSB/TheSkyBlessing pull request #690
Opened 2022-01-11 14:44 UTC by Lapis-LJA

2022-01-20 13:03 UTC, Lapis-LJA commented
ブランチ名がIDと一致してないのはミスです

2022-03-20 18:07 UTC, ChenCMD requested changes

2022-03-20 18:07 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0233.honey_flyer/tick/3.motion.mcfunction
> +        execute if entity @p[tag=Target,distance=30..40] run data modify storage lib: Argument.VectorMagnitude set value 0.8
同じなら要らなさそう

2022-04-23 04:37 UTC, ChenCMD approved these changes

2022-04-23 04:37 UTC, merged