[mob202]狩人の夢を作成
ProjectTSB/TheSkyBlessing pull request #709
Opened 2022-01-13 20:36 UTC by quikku

2022-01-16 17:23 UTC, Cell33 reviewed
0202.hunters_dream/tick/1.skill_sword/2.backstepの8行目、「Argument.VectorMagnitude set value 120」となっていますが、この値は1.2ではないでしょうか？　同じく1.skill_sword/3.stepも160となっています。

2022-01-16 23:43 UTC, quikku commented
> 0202.hunters_dream/tick/1.skill_sword/2.backstepの8行目、「Argument.VectorMagnitude set value 120」となっていますが、この値は1.2ではないでしょうか？　同じく1.skill_sword/3.stepも160となっています。

あーこれね
かぷちなくんがmotionlib変える前だったからこうなっとるのん（てかmotionlibの変更PRもうマスターいったん？）

2022-05-25 10:45 UTC, ChenCMD requested changes

2022-05-25 10:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0202.hunters_dream/attack/2.attack.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-05-25 10:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0202.hunters_dream/tick/1.skill_sword/4.slash.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-05-25 12:05 UTC, ChenCMD approved these changes

2022-05-25 12:05 UTC, merged