神器822：星の音の作成
ProjectTSB/TheSkyBlessing pull request #719
Opened 2022-01-14 20:46 UTC by Lapis-LJA

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo.Damage set value [800-1200]
[800,1200]

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/02.main.mcfunction
> +    execute positioned ~-0.5 ~ ~-0.5 if entity @e[type=#lib:living,type=!player,tag=!Uninterferable,dx=0,limit=1] run function asset:sacred_treasure/0822.sound_of_a_star/trigger/star/03.hit
~-0.5 ~-0.5 ~-0.5じゃないのは意図的？

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/3.main.mcfunction
> +    scoreboard players operation @e[type=marker,tag=MU.Star,distance=..0.01,sort=nearest,limit=1] MU.UserID = @s UserID
ひゅー！！！バグってるぜぇ！！！！！！！！！！！！！！！！！！！！！！はははは！！！！！！！！！！
これ召喚位置違うんだからdistance=..0.01でスコアが付与されるわけがないでしょうがこのデバッグ不足のおたんこなすがぁ！！

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/02.main.mcfunction
> +    schedule function asset:sacred_treasure/0822.sound_of_a_star/trigger/star/01.schedule 1t replace
これ一番下じゃない理由ってある？性癖的に気持ちが悪い。私の性癖が気持ちが悪いという話ではないぞ。

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/02.main.mcfunction
> +    execute if entity @s[tag=MU.3] if score @s MU.Time matches 20.. run tp @s ^ ^ ^1
これmainでmarkerにスコア付与して動かすコマンドを1個にするんじゃダメなんかな

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/02.main.mcfunction
> +    execute if entity @s[tag=MU.3] if score @s MU.Time matches 60.. run kill @s
これmainでmarkerにスコア付与すればコマンド1個になりそう

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/02.main.mcfunction
> +    execute unless block ^ ^ ^1 #lib:no_collision run function asset:sacred_treasure/0822.sound_of_a_star/trigger/star/04.banish
こやつらもtpを実行する前の場所から検知してることになってる

2022-05-17 19:47 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/vfx.mcfunction
> +    particle dust 0.565 0.733 0.733 0.4 ^-0.08034 ^-0.21727 ^ 0 0 0 0 1
おおっとぉ！！！！セレクタァアアアを指定しておりませエエエエエエエエん！！！！！！！！！！！！パーティクルがかぶりましたぁ！！！！！！！！サブ垢を買えエエエエエエエエエエエエエエエエ！！！！

2022-05-24 20:57 UTC, ChenCMD requested changes

2022-05-24 20:57 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/02.main.mcfunction
> +    execute unless block ^ ^ ^1 #lib:no_collision run function asset:sacred_treasure/0822.sound_of_a_star/trigger/star/04.banish
👆

2022-05-24 20:57 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/03.hit.mcfunction
> +    execute as @a if score @s UserID = @e[type=marker,tag=MU.This,distance=..0.01,sort=nearest,limit=1] MU.UserID run function lib:damage/modifier
このdistance=..0.01、tp後にatなしで呼び出されてるので絶対に引っかからなさそう

2022-05-24 20:57 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/trigger/star/03.hit.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-05-25 09:49 UTC, ChenCMD approved these changes

2022-05-25 09:54 UTC, merged