Mob232：ハニーリーダーの作成
ProjectTSB/TheSkyBlessing pull request #738
Opened 2022-01-16 16:19 UTC by Lapis-LJA

2022-04-24 21:06 UTC, ChenCMD requested changes

2022-04-24 21:06 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0187.flame_mage/event/shoot_magic.mcfunction
> +    playsound minecraft:entity.witch.throw hostile @a ~ ~ ~ 2 0.7
混じってます

2022-04-24 21:06 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0232.honey_leader/tick/8.hit.mcfunction
> +    execute as @e[type=zombie,tag=this,scores={MobID=232},distance=..20] run function lib:damage/modifier
```suggestion
    execute as @e[type=zombie,tag=this,distance=..20] run function lib:damage/modifier
```

2022-05-04 18:32 UTC, ChenCMD requested changes

2022-05-04 18:32 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0187.flame_mage/event/shoot_magic.mcfunction
> +    playsound minecraft:entity.witch.throw hostile @a ~ ~ ~ 2 0.7
混じってる

2022-05-04 18:39 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0187.flame_mage/event/shoot_magic.mcfunction
> +    playsound minecraft:entity.witch.throw hostile @a ~ ~ ~ 2 0.7
私視点だと混じってないんだけどなんでなんだ?

2022-05-04 18:51 UTC, ChenCMD approved these changes

2022-05-04 18:52 UTC, merged