Dev/lapis mob0237
ProjectTSB/TheSkyBlessing pull request #744
Opened 2022-01-19 12:48 UTC by Lapis-LJA

2022-05-02 18:30 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/thunder/01.manage.mcfunction
> +    execute if entity @s[scores={6L.Tick=20}] as @p[gamemode=!spectator,distance=..32] facing entity @s eyes rotated ~ 0 positioned as @s run tp @e[type=area_effect_cloud,tag=6L.ThunderSummonPoint,di
as @p[gamemode=!spectator,distance=..32] facing entity @sはなにしてんだ

2022-05-02 18:30 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/magic/01.manage.mcfunction
> +    execute if entity @s[scores={6L.Tick=50}] positioned ~ ~1.6 ~ run function asset:mob/0237.lunatic_mage/skill/magic/03.shoot_beam
anchored eyesでよさそう

2022-05-02 18:30 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/magic/01.manage.mcfunction
> +    execute if entity @s[scores={6L.Tick=20..45}] positioned ~ ~1.6 ~ facing entity @p[gamemode=!spectator,distance=..40] eyes anchored eyes run function asset:mob/0237.lunatic_mage/skill/magic/02.wa
positinedじゃなくてanchored eyesでよさそう

2022-05-02 18:30 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/magic/03.shoot_beam.mcfunction
> +    function asset:mob/0237.lunatic_mage/skill/magic/05.beam_recursive
再帰しただけでヒットしてなくねぇえっすか？！

2022-05-02 18:30 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/04.water_jail_damage.mcfunction
> +        execute as @a[gamemode=!creative,gamemode=!spectator,distance=4..9] at @s run function lib:damage/
at @sいらなさそう

2022-05-02 18:30 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/06.fire.mcfunction
> +    execute if score @s 6L.Tick matches 61.. if score $Temp Temporary matches 0 run function asset:mob/0237.lunatic_mage/skill/elemental_confine/07.shoot_fire
そもそもこれ実行されるの6L.Tickが61以上であるのが確定してるんだから頭のifいらなさそう

2022-05-06 16:07 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/hurt/3.check_health.mcfunction
> +    execute if entity @s[tag=!6L.HealthLess40Per] if score $Health Temporary matches ..40 run tag @s add 6L.HealthLess40Per
リセットをしろ！！！！！！！！！！！！

2022-05-06 16:24 UTC, quikku commented
あとSpawnPointのmarker使うならremoveトリガーをつかえー！

2022-05-06 16:25 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/fire/1.mcfunction
> +    execute if entity @s[scores={6L.Tick=20..}] run scoreboard players operation $Interval Temporary = @s 6L.Tick
$Intervalを定義しろーー！！

2022-05-06 16:25 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/2.water_jail.mcfunction
> +    scoreboard players operation $Temp Temporary %= $6 Const
Tempをリセットしろ！

2022-05-06 16:25 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/fire/1.mcfunction
> +    execute if entity @s[scores={6L.Tick=20..}] run scoreboard players operation $Interval Temporary = @s 6L.Tick
あといろんなところで$TempつかってるけどこれもTempでよくない？

2022-05-06 16:31 UTC, quikku commented
> あとSpawnPointのmarker使うならremoveトリガーをつかえー！
ごめん、あったわ

2022-05-06 17:12 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/1.mcfunction
> +# 雷を落とす
これ同時にやってくるから避けられないんだけど？

2022-05-06 17:12 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/8.thunder.mcfunction
> +# 30のときも3つ落とす
これも常時実行じゃなくてrotatedで60度ずらすだけでよさそう

2022-05-06 17:19 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/1.mcfunction
> +# 水の檻
モブがTPすると同時に発動してくるから走り回ってると確実に当たる上に範囲が狭すぎる

2022-05-06 17:23 UTC, quikku commented on Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/8.thunder.mcfunction
> +# 30のときも3つ落とす
なんでもなかった

2022-05-16 20:25 UTC, quikku commented
クリティカルなバグはないはず
処理が気持ち悪い場合があるがそこは性癖なので...

2022-07-08 11:46 UTC, ChenCMD requested changes

2022-07-08 11:46 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0237.lunatic_mage/0.load.mcfunction
> +    scoreboard objectives add 6L.Count dummy
命名が渋い、`Count`ってなんの回数ですかってなる

2022-07-08 13:59 UTC, ChenCMD approved these changes

2022-07-08 14:00 UTC, merged