[M0174]バーニングブレイズの作成
ProjectTSB/TheSkyBlessing pull request #755
Opened 2022-01-22 06:16 UTC by kaputina

2022-05-23 11:26 UTC, quikku reviewed
私が直します

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/rush.tick.mcfunction
> +    #declare tag Hit
_index.dで指定してる

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.tick.mcfunction
> +    #declare tag Line
複数箇所で指定してるからindex.dのほうがよさそう

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.line.mcfunction
> +execute positioned ~-0.5 ~ ~-0.5 if entity @p[dx=1,dy=1] run playsound minecraft:block.note_block.bell hostile @p[gamemode=!creative,gamemode=!spectator,distance=..32] ~ ~ ~ 1 2 1
positioned ~-1 ~ ~-1じゃないと正の方向にずれる
PlayerShouldInvulnerableタグつかって判定したほうがまるそう

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.shot.loop.mcfunction
> +execute positioned ^ ^ ^ run tag @a[gamemode=!creative,gamemode=!spectator,dx=1,dz=1] add Hit
positioned ~-1 ~-1 ~-1がない

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.shot.mcfunction
> +    #declare tag Line
laser.tickにもある
index.dへ

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.shot.mcfunction
> +execute facing entity @p[gamemode=!creative,gamemode=!spectator,distance=..32] feet anchored eyes run function asset:mob/0174.burning_blaze/action/laser.shot.loop
PlayerShouldInvulnerableタグつかって判定したほうがまるそう

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.tick.mcfunction
> +execute facing entity @p[gamemode=!creative,gamemode=!spectator,distance=..32] feet anchored eyes run function asset:mob/0174.burning_blaze/action/laser.line
PlayerShouldInvulnerableタグ

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/rush.tick.mcfunction
> +execute positioned ^ ^ ^0.5 positioned ~-0.5 ~ ~-0.5 run tag @a[gamemode=!creative,gamemode=!spectator,dx=1,dz=1] add Hit
positioned ~-1 ~ ~-1じゃないと正の方向にずれる
PlayerShouldInvulnerableタグつかって判定したほうが

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/rush.tick.mcfunction
> +execute positioned ^ ^ ^1.0 positioned ~-0.5 ~ ~-0.5 run tag @a[gamemode=!creative,gamemode=!spectator,dx=1,dz=1] add Hit
うえにおなじく

2022-05-23 11:26 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/tick/2.tick.mcfunction
> +    execute if entity @p[gamemode=!creative,gamemode=!spectator,distance=..32] if score $Random Temporary matches 6..10 if score @s 4U.ActionTime matches ..0 run function asset:mob/0174.burning_blaze
PlayerShouldInvulnerable

2022-05-23 11:52 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/attack/2.attack.mcfunction
> +    tag @e[type=arrow,tag=4U.UUIDset,distance=..3,limit=1] remove 4U.UUIDset
ごめん、これなんでこうしてるの？

2022-05-23 12:06 UTC, quikku commented on Asset/data/asset/functions/mob/0229.burning_blaze.shot/tick/2.tick.mcfunction
> +    execute unless block ^ ^ ^1 #lib:air run kill @s
前方壁で自殺はいいけどヒット時に死なないのはいいのかな

2022-05-23 12:22 UTC, kaputina commented on Asset/data/asset/functions/mob/0174.burning_blaze/attack/2.attack.mcfunction
> +    tag @e[type=arrow,tag=4U.UUIDset,distance=..3,limit=1] remove 4U.UUIDset
プレイヤーを燃やすためにFire矢を当ててました、！
ごめんなさいほんと突貫工事で、、、

2022-05-23 12:22 UTC, quikku commented on Asset/data/asset/functions/mob/0174.burning_blaze/attack/2.attack.mcfunction
> +    tag @e[type=arrow,tag=4U.UUIDset,distance=..3,limit=1] remove 4U.UUIDset
okay
アイテム持たせることで解決したぜ

2022-05-23 12:52 UTC, quikku commented
ある程度レビューしてバグも全部なおしたぜグハハハハハハハハアハハハ

2022-07-10 12:16 UTC, ChenCMD requested changes

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0174.burning_blaze/_index.d.mcfunction
> +    #declare objective 4U.NowAction
不要

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0229.burning_blaze.shot/hit.mcfunction
> +    execute as @a[tag=Hit,distance=..5] run function lib:damage/
プレイヤーにしか当たらないのは想定かな

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0229.burning_blaze.shot/hit.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0174.burning_blaze/tick/2.tick.mcfunction
> +    scoreboard players operation $Random Temporary %= $Probability Temporary
$900は定義されてる

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/shot.mcfunction
> +    kill @e[type=marker,tag=Spread]
distance

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/rush.hit.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-07-10 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0174.burning_blaze/action/laser.shot.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-07-10 12:56 UTC, quikku commented on Asset/data/asset/functions/mob/0229.burning_blaze.shot/hit.mcfunction
> +    execute as @a[tag=Hit,distance=..5] run function lib:damage/
モブ壁にされても嫌だから想定でいいんじゃねー？（雑）

2022-07-10 13:22 UTC, ChenCMD approved these changes

2022-07-10 13:24 UTC, merged