謎肉の効果を変更
ProjectTSB/TheSkyBlessing pull request #760
Opened 2022-01-23 02:58 UTC by quikku

2022-01-30 14:40 UTC, ChenCMD approved these changes

2022-01-30 14:41 UTC, ChenCMD requested changes
↑

2022-01-30 14:42 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0105.secret_meat/trigger/bad_effect.mcfunction
> +        data modify storage lib: Argument.BypassResist set value true
そんなのあったんだ
いれとくね

2022-02-01 17:43 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0105.secret_meat/trigger/bad_effect.mcfunction
> +        # data modify storage lib: Argument.FixedDamage set value false
FixedDamage falseだとプレイヤーの攻撃力補正の影響受けるけど本当に大丈夫？

2022-02-01 17:43 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0105.secret_meat/trigger/bad_effect.mcfunction
> +        # data modify storage lib: Argument.FixedDamage set value false
まあ面白いからいいでしょ

2022-02-01 18:00 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0105.secret_meat/trigger/bad_effect.mcfunction
> +        # data modify storage lib: Argument.FixedDamage set value false
ok

2022-02-01 18:00 UTC, ChenCMD approved these changes

2022-02-01 18:16 UTC, merged