[mob216]灰の守護者を作成
ProjectTSB/TheSkyBlessing pull request #784
Opened 2022-02-03 19:51 UTC by quikku

2022-05-25 12:10 UTC, ChenCMD requested changes

2022-05-25 12:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0216.gray_guardian/tick/3.skill_axe/1.skill_axe.mcfunction
> +    #declare score_holder $4tInterval
横着せずちゃんと書いてください
```suggestion
#> Val
# @private
#declare score_holder $4tInterval
```

2022-05-25 12:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0216.gray_guardian/tick/3.skill_axe/3.damage.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-05-25 12:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0216.gray_guardian/tick/4.skill_impact/4.damage.mcfunction
> +    execute as @s run function lib:damage/modifier
as @s

2022-05-25 12:10 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0216.gray_guardian/tick/4.skill_impact/4.damage.mcfunction
> +data remove storage lib: Argument
lib:damage/reset

2022-05-25 12:13 UTC, quikku commented on Asset/data/asset/functions/mob/0216.gray_guardian/tick/1.skill_melee/1.skill_melee.mcfunction
> +# もう一回突進
一応上記のテレポを突進とした意でした...

2022-06-07 19:26 UTC, anitmyan approved these changes

2022-06-07 19:32 UTC, ChenCMD approved these changes

2022-06-07 20:12 UTC, merged