✨ [MOB0210] オーロラアイを作成
ProjectTSB/TheSkyBlessing pull request #815
Opened 2022-02-28 14:29 UTC by Lapis-LJA

2022-03-05 02:16 UTC, quikku reviewed
一応レビュー
あとでちぇんちゃ確認してください

2022-03-05 02:16 UTC, quikku commented on Asset/data/asset/functions/mob/0211.aurora_bullet/tick/3.hit.mcfunction
> +    tag @p[gamemode=!spectator,dx=0] add 5U.Debuff
他@aなのにこれ@pなのは想定された挙動？

2022-03-05 02:16 UTC, quikku commented on Asset/data/asset/functions/mob/0210.aurora_eye/tick/3.attack.mcfunction
> +    execute as @a[gamemode=!spectator,dx=0] run function api:player_modifier/mp_regen/add
HurtTime中に殴られた場合でもこれは発動するけど仕様？
てか別にHurtTimeがいらない気もする

2022-03-05 02:16 UTC, quikku commented on Asset/data/asset/functions/mob/0210.aurora_eye/hurt/2.hurt.mcfunction
> +# @within function asset:mob/0210.aurora_eye/hurt/1.trigger
中身ないやん！

2022-03-05 02:16 UTC, quikku commented on Asset/data/asset/functions/mob/0210.aurora_eye/death/2.death.mcfunction
> +# @within function asset:mob/0210.aurora_eye/death/1.trigger
中身がない！

2022-05-24 20:41 UTC, ChenCMD requested changes

2022-05-24 20:41 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0210.aurora_eye/player_process/02.main.mcfunction
> +    execute if entity @s[scores={5U.DebuffTime=..0}] run function asset:mob/0210.aurora_eye/player_process/04.end
これ`5U.DebuffTime`が0の時、スケジュール予約が行われる上でリセットされない？

2022-05-24 20:41 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0210.aurora_eye/player_process/03.mp_reduction.mcfunction
> +    data remove storage asset:temp MP4Per
resetするもの間違えてる

2022-05-25 09:10 UTC, ChenCMD approved these changes

2022-05-25 10:01 UTC, merged