[262mob]フレストチカを作成
ProjectTSB/TheSkyBlessing pull request #820
Opened 2022-03-07 12:50 UTC by quikku

2022-05-07 19:39 UTC, ChenCMD requested changes

2022-05-07 19:39 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0262.frestchika/tick/move/spread_facing.mcfunction
> +#> asset:mob/0262.frestchika/tick/move/spread_facing
unused....?

2022-05-07 19:51 UTC, quikku commented on Asset/data/asset/functions/mob/0262.frestchika/tick/2.melee/2.first_tick.mcfunction
> +    scoreboard players add @s 7A.Heat 3
あくまでメインはアマスタじゃなくて本体のほうだからそれをするのはなんか...怪しくない？（中身実質アマスタがメインだけど）

2022-05-07 20:14 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0262.frestchika/tick/2.melee/2.first_tick.mcfunction
> +    scoreboard players add @s 7A.Heat 3
そんなに実行が何を主体としてるかは気にしなくて良さそう

2022-05-22 20:59 UTC, ChenCMD approved these changes

2022-05-22 21:00 UTC, merged