✨ [MOB0234] ウォールアイを作成
ProjectTSB/TheSkyBlessing pull request #832
Opened 2022-03-14 19:34 UTC by uran247

機能部分完成
ステータス、移動速度、ロックオン時間、ダメージは要調整？

2022-04-18 11:32 UTC, ChenCMD requested changes
全体的にインデントとコメントのスペースの有無の一貫性のなさが気になる今日この頃

2022-04-18 11:32 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.1.search.mcfunction
> +    #declare score_holder $Soundtime
LocktimeはLock + TimeであってLocktimeって言う1単語ではなさそう、Soundtimeも然り

2022-04-18 11:32 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0234.walleye/0.load.mcfunction
> +    scoreboard objectives add 6i.LockonTime dummy
LockonもLock + onもしくはLock-onな気がするな

2022-04-18 11:32 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.1.search.mcfunction
> +execute positioned ~-5 ~-20 ~-5 if entity @e[tag=Friend,dx=10,dy=20,dz=10] unless score @s 6i.LockonTime matches -2147483648..2147483647 store result score @s 6i.LockonTime run scoreboard players get
store score run score player getよりscore player oprationの方が可読性が高そう
後、19, 20行目に関してはTargetCandidateが存在するか否かを見るだけで良さそうな気がする

2022-04-18 11:32 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.2.move.mcfunction
> +execute at @s if entity @e[tag=Friend,distance=..1] run scoreboard players set @s 6i.Phase 2
これ、奈落に飛んでった時どうなるんだろう

2022-04-18 11:32 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.3.explode.mcfunction
> +# ダメージ: 半径1ブロック以内は60ダメージ、1ブロック離れるごとに10減少
これなら各呼び出し前にダメージの再設定が必要では

2022-04-18 17:14 UTC, uran247 commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.1.search.mcfunction
> +    #declare score_holder $Soundtime
スコアホルダー名修正、36進数も忘れてたので追加

2022-04-18 17:15 UTC, uran247 commented on Asset/data/asset/functions/mob/0234.walleye/0.load.mcfunction
> +    scoreboard objectives add 6i.LockonTime dummy
スコア名を修正

2022-04-18 17:15 UTC, uran247 commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.1.search.mcfunction
> +execute positioned ~-5 ~-20 ~-5 if entity @e[tag=Friend,dx=10,dy=20,dz=10] unless score @s 6i.LockonTime matches -2147483648..2147483647 store result score @s 6i.LockonTime run scoreboard players get
operationに変更したのと19,20はTargetCandidateしか見ないように変更

2022-04-18 17:16 UTC, uran247 commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.2.move.mcfunction
> +execute at @s if entity @e[tag=Friend,distance=..1] run scoreboard players set @s 6i.Phase 2
奈落に行った時も爆発するように修正

2022-04-18 17:16 UTC, uran247 commented on Asset/data/asset/functions/mob/0234.walleye/tick/2.3.explode.mcfunction
> +# ダメージ: 半径1ブロック以内は60ダメージ、1ブロック離れるごとに10減少
ダメージを再設定するようにした。ついでに最後にlib: Argumentのリセットを追加

2022-04-24 13:47 UTC, ChenCMD approved these changes
👁️

2022-04-24 13:52 UTC, merged