0273.hell_bladeと0275.destroyed_blockを作成
ProjectTSB/TheSkyBlessing pull request #837
Opened 2022-03-17 21:03 UTC by yavu

2022-05-08 16:18 UTC, quikku commented on Asset/data/asset/functions/mob/0273.hell_blade/move/.mcfunction
> +
これ中身１コマンドだけどファンクションわける必要ある？

2022-05-08 16:18 UTC, quikku commented on Asset/data/asset/functions/mob/0273.hell_blade/chase/rotate/0.mcfunction
> +    execute run tag @s remove 7L.RotateRight
execute runはけしましょう

2022-05-26 16:57 UTC, Chuzume commented on Asset/data/asset/functions/mob/0273.hell_blade/move/.mcfunction
> +
修正したのん

2022-07-10 08:49 UTC, ChenCMD requested changes

2022-07-10 08:49 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0273.hell_blade/chase/check.mcfunction
> +    execute as @s[y_rotation=-90] unless entity @p[dx=0,dy=4] positioned ~ ~ ~-16 if entity @a[dy=4,dz=16] run function asset:mob/0273.hell_blade/chase/left
これ、手前の`@p[dx=0,dy=4]`の意図が読めないのと、おそらくx,z方向に0.5ずれて判定してると思う

それから、後ろの`if entity @a[~]`も+部分と-部分でおそらくx,z方向にかなりずれてる

2022-07-10 08:49 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0273.hell_blade/break.mcfunction
> +    execute if block ~ ~ ~ #wool unless entity @e[scores={MobID=275},distance=..0.01] run function asset:mob/0275.destroyed_block/summon/2.summon
この召喚方法はやめてほしい(`api:mob/summon`を利用して

2022-07-10 08:49 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0273.hell_blade/landing.mcfunction
> +    data modify entity @s OnGround set value 1b
このfunctionの実行条件が`{OnGround:1b}`だからこれは不要そう

2022-07-10 09:20 UTC, Chuzume commented on Asset/data/asset/functions/mob/0273.hell_blade/chase/check.mcfunction
> +    execute as @s[y_rotation=-90] unless entity @p[dx=0,dy=4] positioned ~ ~ ~-16 if entity @a[dy=4,dz=16] run function asset:mob/0273.hell_blade/chase/left
手前の"@p[dx=0,dy=4]"は、全く同座標に重なられるとその場で回りだすかららしいです。
ずれていることに関しては、"asset:mob/0273.hell_blade/move/"で"align xyz"してるから問題ないそうです。
実際、動作としてはきっちりこっちをブロック単位で捉えてきますね。

2022-07-10 10:31 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0273.hell_blade/chase/check.mcfunction
> +    execute as @s[y_rotation=-90] unless entity @p[dx=0,dy=4] positioned ~ ~ ~-16 if entity @a[dy=4,dz=16] run function asset:mob/0273.hell_blade/chase/left
や、恐らく後ろはalignしててもズレてるはず
-16 ~ -16+16+1の範囲と1 ~ 1+16+1の範囲なので-16 ~ 1と1 ~18の範囲になっていて、最大検知距離にズレがあるはず？

2022-07-11 10:38 UTC, ChenCMD approved these changes

2022-07-11 10:38 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0275.destroyed_block/summon/2.summon.mcfunction
> +#   asset:mob/0273.hell_blade/break
```suggestion
# @within function asset:mob/0275.destroyed_block/summon/1.trigger
```

2022-07-11 11:24 UTC, merged