神器[816-820]かぐや姫装備セットの作成
ProjectTSB/TheSkyBlessing pull request #853
Opened 2022-04-04 18:50 UTC by uran247

2022-05-16 21:33 UTC, quikku approved these changes

2022-05-16 21:33 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0820.jewel_rod_of_horai/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora","Urban","Nyaptov","Wi-ki","Rumor"]
神の追加を想定してこの神だけ使わせる場合を除き、ALLで良さそう

2022-05-16 21:33 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0818.bhuddas_bowl/trigger/3.main.mcfunction
> +    effect give @s slow_falling 1000000 0
全部の処理に言えるんだけど神器によってエフェクトがクリアされた場合消えたままになるのは想定された挙動？

2022-05-16 21:33 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0820.jewel_rod_of_horai/trigger/3.3.2.set_target.mcfunction
> +    execute anchored eyes at @s positioned ^ ^ ^6.4 rotated as @e[tag=MS.BlockChecker,distance=..0.1,x=0.0,y=0.0,z=0.0,sort=furthest,limit=2] positioned ^ ^ ^3.2 rotated as @e[tag=MS.BlockChecker,dis
x=0.0,y=0.0,z=0.0を使う場合、positioned ~-0.5 ~-0.5 ~-0.5を使わないとずれるはず

2022-05-16 21:35 UTC, quikku commented
全然レビューできてないけど気になった点だけレビューした

2022-05-17 19:11 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0820.jewel_rod_of_horai/give/2.give.mcfunction
> +    data modify storage asset:sacred_treasure CanUsedGod set value ["Flora","Urban","Nyaptov","Wi-ki","Rumor"]
直した

2022-05-17 19:16 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0818.bhuddas_bowl/trigger/3.main.mcfunction
> +    effect give @s slow_falling 1000000 0
想定通りの動作です、付け直しを強要させるのをデメリットにしてます。

2022-05-17 19:16 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0820.jewel_rod_of_horai/trigger/3.3.2.set_target.mcfunction
> +    execute anchored eyes at @s positioned ^ ^ ^6.4 rotated as @e[tag=MS.BlockChecker,distance=..0.1,x=0.0,y=0.0,z=0.0,sort=furthest,limit=2] positioned ^ ^ ^3.2 rotated as @e[tag=MS.BlockChecker,dis
直した

2024-04-20 05:28 UTC, haiiro2gou requested changes
セット装備効果をEffect Assetに移し替えたほうが良さそう

2024-04-20 05:28 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.6.damage.mcfunction
> +    execute if score @s MS.AttackLevel matches 2.. as @p[tag=MS.Owner] run function lib:damage/modifier
エラー吐きそう
```suggestion
    execute if score @s MS.AttackLevel matches 2.. as @p[tag=MS.Owner] run function lib:damage/modifier_continuation
```

2024-04-20 05:28 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.6.damage.mcfunction
> +    execute if score @s MS.AttackLevel matches 3.. as @p[tag=MS.Owner] run function lib:damage/modifier
同上
```suggestion
    execute if score @s MS.AttackLevel matches 2.. as @p[tag=MS.Owner] run function lib:damage/modifier_continuation
```

2024-04-20 05:28 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.6.damage.mcfunction
> +    execute if score @s MS.AttackLevel matches 4.. as @p[tag=MS.Owner] run function lib:damage/modifier
同上
```suggestion
    execute if score @s MS.AttackLevel matches 2.. as @p[tag=MS.Owner] run function lib:damage/modifier_continuation
```

2024-04-20 05:28 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.6.damage.mcfunction
lib:damage/をリセットしてないので直してほしい

2024-10-20 10:55 UTC, closed without merging