[mob120]断罪者を作成
ProjectTSB/TheSkyBlessing pull request #866
Opened 2022-04-21 03:11 UTC by quikku

2022-06-01 12:16 UTC, ChenCMD requested changes

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/move/block_check.mcfunction
> +execute positioned ~-1 ~-1 ~-1 if entity @p[dx=0,dy=0,dz=0] run tag @s add PlayerCheck
`~-1 ~-1 ~-1 ~0 ~0 ~0`の範囲なの意図してますか

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/3.slash_attack1.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/3.slash_attack1.mcfunction
> +    execute as @a[gamemode=!creative,gamemode=!spectator,distance=..3] at @s run function lib:damage/
対象がプレイヤーのみなのは意図してる？

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/4.slash_attack2.mcfunction
> +    execute as @a[gamemode=!creative,gamemode=!spectator,distance=..2] run function asset:mob/0120.convict/tick/3.slash/5.percent_damage
対象がプレイヤーのみなのは意図してる？

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/4.slash_attack2.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/particle/thunder_particle2.mcfunction
> +#> asset:mob/0120.convict/tick/particle/thunder_particle2
unused?

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/particle/thunder_particle.mcfunction
> +#> asset:mob/0120.convict/tick/particle/thunder_particle
unused?

2022-06-01 12:16 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/player_process/2.main.mcfunction
> +    execute if entity @s[scores={3C.Time=..0}] run function asset:mob/0120.convict/player_process/3.reset
Time=0の時にscheduleが予約された上でresetされる

2022-06-01 12:33 UTC, quikku commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/4.slash_attack2.mcfunction
> +    execute as @a[gamemode=!creative,gamemode=!spectator,distance=..2] run function asset:mob/0120.convict/tick/3.slash/5.percent_damage
generic.max_healthで割合とってるからまあ想定

2022-06-01 12:35 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/3.slash_attack1.mcfunction
> +    execute as @a[gamemode=!creative,gamemode=!spectator,distance=..3] at @s run function lib:damage/
巻き込むだけ巻き込んでプレイヤーがいないなら2は発動しない的なの方が綺麗そう感

2022-06-01 12:36 UTC, quikku commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/3.slash_attack1.mcfunction
> +    execute as @a[gamemode=!creative,gamemode=!spectator,distance=..3] at @s run function lib:damage/
んじゃそうするかー

2022-06-13 19:28 UTC, ChenCMD requested changes

2022-06-13 19:28 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/2.summon/2.first_tick.mcfunction
> +        execute if score $Count Temporary matches 6.. run tp @e[type=skeleton,scores={MobID=90},distance=..50,limit=2] ~ -999 ~
2?? 3??

2022-06-13 19:28 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/1.axe/3.impact.mcfunction
> +    execute as @e[type=#lib:living,tag=Friend,tag=!PlayerShouldInvulnerable,distance=..2.3] run function lib:damage/
Uninterferableは消さないで....

2022-06-13 19:28 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0120.convict/tick/3.slash/3.slash_attack1.mcfunction
> +    execute as @e[type=#lib:living,tag=Friend,tag=!PlayerShouldInvulnerable,distance=..3] at @s run function lib:damage/
Uninterferableは消さないで....

2022-07-04 17:36 UTC, ChenCMD approved these changes

2022-07-04 17:37 UTC, merged