🚸 [MOB0078] 雷鳴之使を強化
ProjectTSB/TheSkyBlessing pull request #867
Opened 2022-04-22 15:45 UTC by Lapis-LJA

2022-05-07 07:11 UTC, quikku commented on Asset/data/asset/functions/mob/0078.messenger_of_thunder/skill/1/2.thunder_point.mcfunction
> +    data modify storage lib: Argument.Bounds set value [[3d,3d],[0],[3d,3d]]
[3d,3d],[0d,0d],[3d,3d]

2022-05-07 07:11 UTC, quikku commented on Asset/data/asset/functions/mob/0078.messenger_of_thunder/tick/reset.mcfunction
> +    execute if entity @s[scores={26.Tick=0..}] run scoreboard players set @s 26.Tick -80
execute if entity @s[scores={26.Tick=0..}]いらない

2022-05-07 07:11 UTC, quikku commented on Asset/data/asset/functions/mob/0078.messenger_of_thunder/skill/4/2.activate.mcfunction
> +    execute rotated ~ 0 facing entity @p[gamemode=!spectator,distance=..50] feet run tp @e[type=marker,scores={MobID=82},distance=..0.001,sort=nearest,limit=1] ~ ~ ~ ~ ~
rotatedが後ろ

2022-05-07 07:11 UTC, quikku commented on Asset/data/asset/functions/mob/0078.messenger_of_thunder/tick/2.tick.mcfunction
> +    execute if entity @s[scores={26.TPCool=0..}] run scoreboard players remove @s 26.TPCool 1
26.tickは上がるのにこいつは下がるのが気に食わない

2022-07-10 09:39 UTC, ChenCMD requested changes

2022-07-10 09:39 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0078.messenger_of_thunder/skill/1/5.thunder_attack.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-07-10 12:18 UTC, ChenCMD approved these changes

2022-07-10 12:18 UTC, merged