[神器933]オートトーチを作成
ProjectTSB/TheSkyBlessing pull request #879
Opened 2022-04-28 20:51 UTC by quikku

2022-05-03 20:41 UTC, ChenCMD requested changes

2022-05-03 20:41 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0933.auto_torch/trigger/can_set_check.mcfunction
> +    execute if block ~ ~-1 ~ #lib:air run tag @s add FailRecovery
これだといずれかの条件満たすだけでFailRecovery付きませんか

2022-05-03 21:17 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0933.auto_torch/trigger/can_set_check.mcfunction
> +    execute if block ~ ~-1 ~ #lib:air run tag @s add FailRecovery
execute if entity @s[tag=CanUsed,tag=FailRecovery] run tag @s remove CanUsed
だからFailRecoveryがどれか一個でも満たされた時点でCanUsedが外されるみたいな感じだと思う

2022-05-04 18:29 UTC, ChenCMD approved these changes

2022-05-04 18:33 UTC, merged