[神器253]ホーリーバリアを作成
ProjectTSB/TheSkyBlessing pull request #882
Opened 2022-05-01 14:33 UTC by uran247

2022-05-03 20:24 UTC, ChenCMD reviewed
コメントのインデントが気になる今日このごろ

2022-05-03 20:24 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0253.holy_barrier/trigger/3.main.mcfunction
> +    tag @e[type=#lib:living,tag=!Enemy.Boss,predicate=asset:sacred_treasure/0253.holy_barrier/is_angry] add 71.Target
```suggestion
    tag @e[type=#lib:living,tag=!Enemy.Boss,tag=!Uninterferable,predicate=asset:sacred_treasure/0253.holy_barrier/is_angry] add 71.Target
```

2022-05-03 20:25 UTC, ChenCMD requested changes
Ctrl + EnterがCommentなの罠だろ

2022-05-04 21:36 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0253.holy_barrier/trigger/3.main.mcfunction
> +    tag @e[type=#lib:living,tag=!Enemy.Boss,predicate=asset:sacred_treasure/0253.holy_barrier/is_angry] add 71.Target
修正実施

2022-05-05 04:51 UTC, ChenCMD approved these changes

2022-05-05 17:21 UTC, merged