[神器0930]Z旗を作成
ProjectTSB/TheSkyBlessing pull request #889
Opened 2022-05-03 19:12 UTC by uran247

海軍旗の方です

2022-05-03 19:27 UTC, ChenCMD requested changes

2022-05-03 19:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/3.main.mcfunction
> +    execute if entity @s[tag=!PU.Modifier] run function api:player_modifier/defense/base/add
Argumentのリセットが無いので`PU.Modifier`が付いてる場合そのままになるので必要っぽい

2022-05-03 19:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/dis_equip/main.mcfunction
> +    execute if score $PU.ItemNumber Temporary matches ..1 if entity @s[tag=PU.Modifier] run tag @s[tag=PU.Modifier] remove PU.Modifier
こっちも同様

2022-05-04 21:17 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/3.main.mcfunction
> +    execute if entity @s[tag=!PU.Modifier] run function api:player_modifier/defense/base/add
引数のリセットを追加した

2022-05-04 21:17 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/dis_equip/main.mcfunction
> +    execute if score $PU.ItemNumber Temporary matches ..1 if entity @s[tag=PU.Modifier] run tag @s[tag=PU.Modifier] remove PU.Modifier
引数のリセットを追加した

2022-05-07 06:44 UTC, ChenCMD approved these changes

2022-05-07 20:57 UTC, merged