神器364：赤い騎士の剣のデメリットの強化
ProjectTSB/TheSkyBlessing pull request #905
Opened 2022-05-08 09:05 UTC by Lapis-LJA

2022-05-08 09:12 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0364.red_knights_sword/trigger/3.main.mcfunction
> +    data remove storage lib: Argument
後ろの方で消してるからここいらない

2022-05-09 07:25 UTC, ChenCMD requested changes

2022-05-09 07:25 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0365.bloodthirsty_sword/trigger/3.main.mcfunction
> +        execute store result storage lib: Argument.Damage float 0.3 run data get entity @s Health
API使ってください

2022-05-09 08:52 UTC, ChenCMD approved these changes

2022-05-10 20:55 UTC, merged