✨ [神器0613] コール：フルストゥーカを作成
ProjectTSB/TheSkyBlessing pull request #914
Opened 2022-05-11 17:30 UTC by quikku

2022-05-16 20:51 UTC, quikku commented on Asset/data/asset/functions/mob/0282.call_fulstuka/tick/spreadteleport.mcfunction
> +   execute at @s run playsound minecraft:entity.enderman.teleport hostile @a ~ ~ ~ 0.7 0.9 0
敵じゃねぇだろばか

2022-05-25 05:59 UTC, ChenCMD requested changes

2022-05-25 05:59 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0282.call_fulstuka/tick/spreadteleport.mcfunction
> +   execute at @s run playsound minecraft:entity.enderman.teleport hostile @a ~ ~ ~ 0.7 0.9 0
👆

2022-05-25 05:59 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0282.call_fulstuka/tick/1.skill_gun/5.damage.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-05-25 05:59 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0282.call_fulstuka/tick/2.skill_melee/3.slash.mcfunction
> +    data remove storage lib: Argument
lib:damage/reset

2022-05-25 05:59 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0282.call_fulstuka/tick/2.skill_melee/1.skill_melee.mcfunction
> +# 突進でプレイヤーが見つかってスコアが飛んだ先
このコメントの意味が理解出来ない()

2022-05-25 06:15 UTC, quikku commented on Asset/data/asset/functions/mob/0282.call_fulstuka/tick/2.skill_melee/1.skill_melee.mcfunction
> +# 突進でプレイヤーが見つかってスコアが飛んだ先
（コピペして治すの忘れたやつですごめん）

2022-05-25 11:03 UTC, ChenCMD approved these changes

2022-05-25 11:26 UTC, merged