【神器0953 メテオレインを作成】
ProjectTSB/TheSkyBlessing pull request #918
Opened 2022-05-12 17:42 UTC by Chuzume

2022-07-10 13:53 UTC, ChenCMD requested changes

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/give.json
> +>>>>>>> master
Conflict解消し忘れてる

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/register.mcfunction
> +#> asset:sacred_treasure/0953.meteor_rain/register
tag/function側書き忘れてる？？

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/trigger/_index.d.mcfunction
> +# @within function asset:sacred_treasure/0953.meteor_rain/trigger/**
***UNUSED***

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/trigger/event/summon.mcfunction
> +    kill @e[type=marker,tag=SpreadMarker]
distanceほしい

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0284.meteor_rain_entity/tick/event/init.mcfunction
> +    kill @e[type=marker,tag=SpreadMarker,limit=1]
distance

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0285.meteor_rain_emitter/tick/event/summon_meteor.mcfunction
> +   kill @e[type=marker,tag=EntitySpreader]
distance

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0285.meteor_rain_emitter/_index.d.mcfunction
> +    #declare
***UNUSED***

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0285.meteor_rain_emitter/0.load.mcfunction
> +    scoreboard objectives add 7X.Count dummy
スコア名がかなり分かりづらいかも

2022-07-10 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/trigger/event/summon.mcfunction
> +#> asset:sacred_treasure/0953.meteor_rain/trigger/event/summon
そもそも呼び出し元がない？

2022-07-11 07:01 UTC, Chuzume commented
今見てみると、モブの方の処理に飛んでいくの、すごく見づらい気がしたので神器内に全部格納しました。
レビューでの修正点は全て解決していますが、二度も見れるかと感じるようなら、これをクローズしてくれて構いません。

2022-07-11 10:28 UTC, ChenCMD approved these changes

2022-07-11 10:30 UTC, merged