神器952：狂月の杖を作成
ProjectTSB/TheSkyBlessing pull request #959
Opened 2022-05-27 15:49 UTC by Lapis-LJA

2022-05-27 17:38 UTC, quikku commented
多分よさそう

2022-06-01 10:03 UTC, ChenCMD requested changes

2022-06-01 10:03 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0952.lunatic_rod/trigger/rejoin_process.mcfunction
> +    execute if entity @a[scores={QG.EffectTime=0..}] run schedule function asset:sacred_treasure/0952.lunatic_rod/trigger/effect/loop 1t replace
rejoinって@sでよくないっけ

2022-06-01 10:03 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0952.lunatic_rod/trigger/effect/loop.mcfunction
> +    execute if entity @a[scores={QG.EffectTime=0..}] as @a[scores={QG.EffectTime=0..}] at @s run function asset:sacred_treasure/0952.lunatic_rod/trigger/effect/main
基本的にいるでしょ
```suggestion
    execute as @a[scores={QG.EffectTime=0..}] at @s run function asset:sacred_treasure/0952.lunatic_rod/trigger/effect/main
```

2022-06-01 10:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/sacred_treasure/0952.lunatic_rod/trigger/3.main.mcfunction
> +    execute anchored eyes run function asset:sacred_treasure/0952.lunatic_rod/trigger/4.recursive
最初の1回の位置がおかしくなる、というのは1回目はプレイヤーの目の位置で実行される、ということでいいんだよね？

2022-06-02 17:52 UTC, ChenCMD approved these changes

2022-06-02 17:57 UTC, merged