[神器172]つららを作成
ProjectTSB/TheSkyBlessing pull request #973
Opened 2022-06-05 20:18 UTC by quikku

2022-06-17 12:06 UTC, ChenCMD requested changes

2022-06-17 12:12 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0172.icicle/trigger/laser/particle_specal.mcfunction
> +#> asset:sacred_treasure/0172.icicle/trigger/laser/particle_specal
妥当な名前がなんも思いつかなかったんや...

2022-06-17 12:14 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0172.icicle/trigger/laser/particle_specal.mcfunction
> +#> asset:sacred_treasure/0172.icicle/trigger/laser/particle_specal
<img width="229" alt="image" src="https://user-images.githubusercontent.com/46134240/174296027-7bea481f-fc88-4bce-b6e4-3efe98ad2805.png">

2022-06-17 13:23 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0172.icicle/trigger/laser/particle_specal.mcfunction
> +#> asset:sacred_treasure/0172.icicle/trigger/laser/particle_specal
そっちかーーー

2022-07-04 17:28 UTC, ChenCMD approved these changes

2022-07-04 17:30 UTC, merged