【神器0978 & 0979 & 0980】火、水、雷のチャームを作成
ProjectTSB/TheSkyBlessing pull request #986
Opened 2022-06-19 07:45 UTC by Chuzume

火炎のリングより大きく強化してくれますが、その代わりに一つの属性しか強化しません。

2022-06-19 07:48 UTC, quikku commented
雑に見たんだけどこれ問題がありそう
複数個持ってる状態から一つだけ外した場合に補正がなくなる
軽装のチャームとか火炎のリングみたいなdis_equipにしてね

2022-06-28 05:08 UTC, ChenCMD requested changes

2022-06-28 05:08 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/give.json
> +        "asset:sacred_treasure/0978.fire_charm/give/1.trigger",
```suggestion
        "asset:sacred_treasure/0980.thunder_charm/give/1.trigger",
        "asset:sacred_treasure/0979.water_charm/give/1.trigger",
        "asset:sacred_treasure/0978.fire_charm/give/1.trigger",
```

2022-07-04 17:31 UTC, ChenCMD approved these changes

2022-07-04 17:35 UTC, merged