【神器976】ブレイブソードを作成
ProjectTSB/TheSkyBlessing pull request #987
Opened 2022-06-19 20:34 UTC by Chuzume

・中盤の武器みたいな名前と見た目ですが、ランク4。
・斬撃は持続判定にしたい感じもしますが、ダメージ表示がやかましかったので、1F判定です。
・珍しく近距離武器なのでDPSはちょっと高めに設定しています。
![image](https://user-images.githubusercontent.com/46894504/174499375-8c474bba-175f-44fb-8576-5e639aeeb099.png)

2022-07-10 13:40 UTC, ChenCMD requested changes

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/combo/slash1.mcfunction
> +    execute positioned ^ ^ ^1.5 as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2] run function asset:sacred_treasure/0976.brave_sword/trigger/combo/damage
tag=EnemyがないからNPCとかにあたる気がする

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/combo/slash2.mcfunction
> +    execute positioned ^ ^ ^1.5 as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2] run function asset:sacred_treasure/0976.brave_sword/trigger/combo/damage
tag=EnemyがないからNPCとかにあたる気がする

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/combo/slash3.mcfunction
> +    execute positioned ^ ^ ^1.5 as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2] run function asset:sacred_treasure/0976.brave_sword/trigger/combo/damage
tag=EnemyがないからNPCとかにあたる気がする

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/combo/slash3.mcfunction
> +    execute as @e[type=armor_stand,tag=R4.SlashShotInit] at @s run function asset:sacred_treasure/0976.brave_sword/trigger/slash_shot/init
distance

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/slash_entity/init.mcfunction
> +    execute store result entity @s Pose.RightArm[2] float -1 run scoreboard players remove @s Temporary 90
api:data_get/rotation使ってください

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/slash_entity/2.main.mcfunction
> +    tag @a[tag=R4.OwnerPlayer] remove R4.OwnerPlayer
今はOwnerPlayer不要っぽい？

2022-07-10 13:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/slash_shot/3.hit.mcfunction
> +    execute as @a[tag=R4.OwnerPlayer] run function lib:damage/modifier
OwnerPlayerの特定忘れてる？

2022-07-11 02:46 UTC, Chuzume commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/combo/slash2.mcfunction
> +    execute positioned ^ ^ ^1.5 as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2] run function asset:sacred_treasure/0976.brave_sword/trigger/combo/damage
オートターゲットの攻撃ではない（扱いとしては左クリックパンチとかと一緒)のつもりなので、そこらの動物とかを薙ぎ払うためにこうしました。この辺はマイクラ的に味方にも当たるか、世のゲームみたく味方には当たらないようにするかは後で考えます

2022-07-11 02:59 UTC, Chuzume commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/combo/slash2.mcfunction
> +    execute positioned ^ ^ ^1.5 as @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..2] run function asset:sacred_treasure/0976.brave_sword/trigger/combo/damage
あと、コレと同じターゲットの取り方する神器が結構あるので、どちらに合わせればいいか全く分からない状態です。tag=Enemyにするとひつじしゃんを片付けられなくなったりしません？

2022-07-11 10:36 UTC, ChenCMD requested changes

2022-07-11 10:36 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0976.brave_sword/trigger/slash_entity/init.mcfunction
> +    execute store result entity @s Pose.RightArm[2] float -1 run scoreboard players remove @s Temporary 90
これで良い/これじゃないとダメな気がする
```suggestion
# 向きを揃える
    execute as @p[tag=this] run function api:data_get/rotation
    data modify entity @s Rotation set from storage api: Rotation

# 向き
    execute store result score @s Temporary run data get storage api: Rotation[1] 100
    execute store result entity @s Pose.RightArm[2] float -0.01 run scoreboard players remove @s Temporary 9000
```

2022-07-11 17:08 UTC, ChenCMD approved these changes

2022-07-11 17:08 UTC, merged